src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <description>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</description>
        <externalId>true</externalId>
        <inlineHelpText>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</inlineHelpText>
        <label>SAP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; Indicates that the record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Frontier_VisitListRecords_Test.cls
/***********************************************************************************************
* @author : Cognizant technology solutions.
* @version : 1.0
* @objects Referenced :Account,Event,Account Business Role,Territory
* @Description : This test class is covering code lines for apex class "Frontier_VisitListRecords"
*************************************************************************************************/

@isTest
public class Frontier_VisitListRecords_Test {
    
    @testSetup
    static void setup(){
        TestUtilClass.createTestUsers('System Administrator',2);
        TestUtilClass.createTestAccount(3);
        TestUtilClass.createContact(3);
        TestUtilClass.createTestEvent(2);
        TestUtilClass.createTestAccountRole(2);
     }
    static testmethod void getDetails() {
        list<account> accountList;
        Set<Id> accountIds = new Set<Id>();
        list<event> eventList;
        list<AccountShare> shareList;
        list<Group> groupList;
        list<Territory2> territoryList;
        list<user> userlist= [SELECT id,profile.name FROM user WHERE profile.Name ='System Administrator' AND IsActive=true LIMIT 1];
        system.debug('@@userslist'+userlist);
        Map<Id,Account_Business_Role__c> bussinessroleMap = new Map<Id,Account_Business_Role__c>();
        Map<Id,Territory2> UserTerritoryMap = new Map<Id,Territory2>();
        if(!userlist.isEmpty()){
            system.runAs(userlist[0])
            {     
                accountList= new list<account>();
                
                accountList=[SELECT Id,Name FROM Account LIMIT 10];
                System.debug(accountList + 'accountList');
                
                if(!accountList.isEmpty()){
                    List<Account_Business_Role__c> bussinessRoleList =[SELECT Id,SAP_ID__c,Service_Level_Class_Descr__c,Account_SFID__c FROM Account_Business_Role__c WHERE Account_SFID__c=:accountList[0].Id AND Archive_Ind__c = 'N']; 
                    for(Account_Business_Role__c accbussinessrole : bussinessRoleList){
                      if(!bussinessroleMap.containsKey(accbussinessrole.Account_SFID__c))
                         bussinessroleMap.put(accbussinessrole.Account_SFID__c, accbussinessrole);
                         } 
                   
                    eventList= [SELECT Description,StartDateTime,EndDateTime,ActivityDate,AccountId,CreatedDate,Who.Name,What.Name,Type  FROM event WHERE WhatId=:accountList[0].Id LIMIT 10 ];
                    if(!eventList.isEmpty()){
                        for(Event event : eventList){
                        if(!accountIds.contains(event.whatId)){
                         accountIds.add(event.WhatId);
                    } 
                        }
                    }
                        else{
                        eventList = new list<event>();
                    }
                   
                }
               
                try{
                    String todayDate = String.valueof(Date.today().month());
                    if(!accountList.isEmpty()) { 
                        
                         //Frontier_VisitListRecords.visitRecordMapping(eventList,bussinessroleMap,UserTerritoryMap);
                        Frontier_VisitListRecords.Status ='Positive';
                          Frontier_VisitListRecords.getVisitDetails(1,10,'Phone Call','None',todayDate,'US',true);
Frontier_VisitListRecords.Status ='Negative';
                        delete bussinessroleMap.values();
                        Frontier_VisitListRecords.getVisitDetails(1,10,'Phone Call','Develop',todayDate+';12','US',true);
                        
                        Frontier_VisitListRecords.getVisitDetails(1,10,'Phone Call','Develop','','US',true);                        
                        Frontier_VisitListRecords.getVisitDetails(1,10,'Event','None','12','US',true);
                    }
                }
                
                catch(ListException le) {
                    System.debug('Message: ' + le.getMessage() + 'Cause: ' + le.getCause() + 'Line number: ' + le.getLineNumber() + 'Stack trace: ' + le.getStackTraceString());    
                } 
                System.assert(!accountList.isEmpty(),'Accounts Created');
                
            }
        }
    }
    }