src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <description>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</description>
        <externalId>true</externalId>
        <inlineHelpText>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</inlineHelpText>
        <label>SAP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FRRest_GME_PersistanceTest.cls
/* ************************************************************************************************************
 * Category             :   Apex Class
 * Name                 :   FRRest_GME_PersistanceTest
 * Description          :   This test class is covering code lines for apex class "FRRest_GME_Persistance"
 * Author               :   Cognizant Technology Solutions
 * ************************************************************************************************************/
@isTest
public class FRRest_GME_PersistanceTest {

@testsetup
    static void accountsetup()
    {   
            TestUtilClass.createTestUsers('System Administrator',2);
            TestUtilClass.createTestAccount(4);
            TestUtilClass.createTestAccountRole(4);
       TestUtilClass.createTestAccountCommunication(4);

    }
        public static testMethod void testingAccs()
        {
            Test.startTest();
            //[select id,Role_Descr__c,Service_Level_Class_Descr__c,SAP_ID__c,Account_SFID__c from Account_Business_Role__c Limit 1];
            String response = '{"queueDuration":3,"queryDuration":319,"results":[{"resultSet":true,"data":[{"DLR_SAP_ID":"00010222120","DLR_RADL_CD":"Develop"},{"DLR_SAP_ID":"0001022262","DLR_RADL_CD":"Develop"},{"DLR_SAP_ID":"0001022329","DLR_RADL_CD":"Develop"},{"DLR_SAP_ID":"0001022173","DLR_RADL_CD":"Light Touch"},{"DLR_SAP_ID":"0001022192","DLR_RADL_CD":"Acquire"},{"DLR_SAP_ID":"0001022164","DLR_RADL_CD":"Light Touch"},{"DLR_SAP_ID":"0001022334","DLR_RADL_CD":"Retain"}],"rowCount":7,"rowLimitExceeded":false}]}';
            /*List<FRRestAccDetail.Responsewrapper> liResponses = new List<FRRestAccDetail.Responsewrapper>();
            liResponses.add((FRRestAccDetail.Responsewrapper)JSON.deserialize(response,FRRestAccDetail.Responsewrapper.Class));*/
            FRRest_GME_Persistance.updateAccountInfo(response);
            //System.assertEquals('00010222120',ab[0].SAP_ID__c);
            Test.stopTest();
        }
}