src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <description>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</description>
        <externalId>true</externalId>
        <inlineHelpText>TEMPORARY ONLY - Long term solution is to use an Account Identifier object since the same account may have multiple SAP ID&apos;s associated with it.</inlineHelpText>
        <label>SAP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Identifier__c.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field primarily indicates if it is a Grower or a Dealer and the brand if applicable.</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Identifiers</relationshipLabel>
        <relationshipName>Account_Identifiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account to which the Identifier maps to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Identifiers</relationshipLabel>
        <relationshipName>Account_Identifiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_System_ID__c</fullName>
        <description>Unique identifier fro an account from the source system</description>
        <externalId>true</externalId>
        <label>Identifier</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Account Identifier</label>
    <nameField>
        <label>Account Identifier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Identifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FRRest_GME_Persistance.cls
/* ************************************************************************************************************
 * Category             :   Apex Class
 * Name                 :   FRRest_GME_Persistance
 * Description          :   This class is receiving response form a call out class "FRRestAccDetail", updating 
 *                          the RADL data in the Account Business Role.
 * Author               :   Cognizant Technology Solutions
 * Last Modified Date   :    8/27/2016 3:01 AM
 * ************************************************************************************************************/
public class FRRest_GME_Persistance {
    
   @future(callout=true)
    public static void updateAccountInfo(String responseResults)
    {
        List<FRRestAccDetail.Responsewrapper> result = new  List<FRRestAccDetail.Responsewrapper>();
        if(responseResults != null){
        result.add((FRRestAccDetail.Responsewrapper)JSON.deserialize(responseResults,FRRestAccDetail.Responsewrapper.Class));
        }
        Map<String,String> SAPIds = new Map<String,String>();
        List<Account_Business_Role__c> businessRoles = new List<Account_Business_Role__c>();        
        for(FRRestAccDetail.ResponseData ref: result[0].results[0].data){ 
            SAPIds.put(ref.DLR_SAP_ID,ref.DLR_RADL_CD);
        }
        if(!SAPIds.isEmpty()){
            //for(Account_Business_Role__c businessRole : [SELECT Id,SAP_ID__c,Service_Level_Class_Descr__c FROM Account_Business_Role__c]){
             for(Account_Business_Role__c businessRole : [SELECT Id,(SELECT Source_System_ID__c FROM Account_Identifiers__r LIMIT 1),Service_Level_Class_Descr__c FROM Account_Business_Role__c]){
                // If GME Account exist in External System and RADL has value then updates RADL, else updating the value as unknown.
                String identifierapnd = businessRole.Account_Identifiers__r[0].Source_System_ID__c;
                 If(SAPIds.containsKey(identifierapnd)){
                    businessRole.Service_Level_Class_Descr__c = SAPIds.get(identifierapnd) != null ? SAPIds.get(identifierapnd) : 'Unknown';    
                }else{
                    // If GME Account does not exist in External System, updating GME Account RADL as Unknown
                    businessRole.Service_Level_Class_Descr__c = 'Unknown';
                }
                businessRoles.add(businessRole);
            }
        }
        if(!businessRoles.isEmpty()){
            update businessRoles;
        }
        
    }
}