src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Frontier_LocationActivities.cls
public class Frontier_LocationActivities {
    @AuraEnabled
    public static list<task> getMyLocationRecords(decimal lati,decimal longi){
        system.debug('Latitude=>'+lati);
        system.debug('Longitude=>'+longi);
            List<Account> acc = Database.Query('Select Id,Name,(select Service_Level_Class_Descr__c From Business_Roles__r),(select Id,subject,Type,ActivityDate,Who.Name,Account.Name, Account.BillingCity, Account.BillingStreet,Account.BillingLatitude,Account.BillingLongitude,Status,priority from Tasks where Remind_me_at_Location__c = True and isClosed = False) from Account where Distance(BillingAddress,Geolocation('+lati+','+longi+'),\'mi\') < 30 limit 10');
        List<task> taskRecords = new List<task>();        
        for(Account accountRecords : acc ){
            for(Task tk:accountRecords.tasks)
                taskRecords.add(tk);
        }  
        system.debug('taskRecords=>'+taskRecords);

        return taskRecords;
    }
    
    @AuraEnabled
    public static list<Account> getCoverageAreaLocationRecords(decimal lati,decimal longi){
        system.debug('Latitude=>'+lati);
        system.debug('Longitude=>'+longi);
        List<Account> acc = Database.Query('Select Id,Name,BillingLongitude,BillingLatitude,(select Service_Level_Class_Descr__c From Business_Roles__r),(select Id,subject,Type,ActivityDate,Who.Name,Account.Name, Account.BillingCity, Account.BillingStreet,Account.BillingLatitude,Account.BillingLongitude,Status,priority from Tasks where Remind_me_at_Location__c = True and isClosed = False) from Account where Distance(BillingAddress,Geolocation('+lati+','+longi+'),\'mi\') < 30 limit 10');
        system.debug('taskRecords=>'+acc);
        return acc;
    }
}