src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Descr__c</fullName>
        <description>Busines Unit/Line of Business associated with the Role.  Not all areas will have need to call out a specific line of business.  Example: &quot;Ag Chem&quot;, &quot;National&quot;, &quot;Channel&quot;, etc.</description>
        <inlineHelpText>Busines Unit/Line of Business associated with the Role.</inlineHelpText>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Seed and Traits</fullName>
                </value>
                <value>
                    <fullName>Agroceres</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Unit/Business Role etc. related to Account Business Role</description>
        <label>Parent Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Account_Business_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Communication__c.object
<CustomObject>
    <description>Link Accounts to their associated Addresses, Phone Numbers, Emails, etc..  Many-to-many relationship.</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</description>
        <inlineHelpText>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</inlineHelpText>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Communication</description>
        <inlineHelpText>Account related to the Communication</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Address/Phone/Email/etc. related to the Account Communication Role</description>
        <inlineHelpText>Account Address/Phone/Email/etc. related to the Account Communication Role</inlineHelpText>
        <label>Parent Account Communication</label>
        <referenceTo>Account_Communication__c</referenceTo>
        <relationshipLabel>Account Communication</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Role for the Account Communication</description>
        <inlineHelpText>Role for the Account Communication</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Addr__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Communication</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Account Communication Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Communications</pluralLabel>
    <recordTypes>
        <fullName>Account_Communication_Address_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for physical address&apos; role&apos;s Business Role.</description>
        <label>Address Role Business Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAccountListController.cls
/* 
*
* @author : Cognizant technology solutions.
* @version : 1.0
* @objects Referenced :Account,Event,Account Communications,Account Business Role 
* @Description : This test class is covering code lines for apex class "AccountListController"
*/

@isTest
Public class TestAccountListController {
    @testSetup
    static void setup(){
        TestUtilClass.createTestUsers('System Administrator',2);
        TestUtilClass.createTestAccount(10);
        TestUtilClass.createTestGrowerAccount(2);
        TestUtilClass.createContact(4);
        TestUtilClass.createTestEvent(2);
        TestUtilClass.createTestAccountRole(5);
        TestUtilClass.createTestAccountCommunication(5);
        
    }
    static testmethod void getDetails() {
        list<user> userlist= [select id,profile.name from user where profile.Name ='System Administrator' and IsActive=true Limit 1];
        if(!userlist.isEmpty()){
            system.runAs(userlist[0]){     
                list<account> accountList=[SELECT Id,Name FROM Account LIMIT 10];
                List<Account_Communication__c> accCommunication;
                try { 
                    if(!accountList.isEmpty()){
                    RecordType strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account_Communication__c' and DeveloperName = 'Account_Communication_Address_Role_Business_Role' LIMIT 1];
                    Account_Business_Role__c bussinessRole =[SELECT Id FROM Account_Business_Role__c where Account_SFID__c=:accountList[0].Id AND Archive_Ind__c = 'N'
                                                             LIMIT 1]; 
                    bussinessRole.Business_Unit_Descr__c='National';
                    update bussinessRole;
                    
                    accCommunication= [SELECT Street_Addr__c,Parent_SFID__c,RecordTypeId FROM Account_Communication__c 
                         WHERE Account_SFID__c=: accountList[0].id  AND Archive_Ind__c = 'N'];
                    
                    // Update the Account Communication fields.
                        if(!accCommunication.isEmpty()){
                            accCommunication[0].recordTypeId = strRecordTypeId.Id;
                            accCommunication[0].Account_Business_Role_SFID__c=bussinessRole.Id;
                            accCommunication[0].Parent_SFID__c= accCommunication[1].Id;
                            accCommunication[1].Parent_SFID__c =  accCommunication[2].Id; 
                            accCommunication[1].Role_Descr__c ='Business';
                            // Make the update call.
                            update accCommunication;
                        }
                   } 
                }
                catch(DmlException e) {
                    System.debug('An unexpected error has occurred: ' + e.getMessage());
                }
                
                Test.startTest(); 
                try{                                  
                    if(!accountList.isEmpty()){
                        AccountListController.getAccounts(accountList[0].Name,1,-1);
                        AccountListController.getAccounts(accountList[0].Name,3,1);  
                        AccountListController.sortBy('Develop',3,1);
                        AccountListController.sortBy('',3,-1); 
                        Frontier_GrowerAccountListController.getAccounts(accountList[0].Name,1,-1,accountList[0].Id);
                        Frontier_GrowerAccountListController.getAccounts(accountList[0].Name,3,1,accountList[0].Id);  
                        Frontier_GrowerAccountListController.sortBy('Develop',3,1,accountList[0].Id);
                        Frontier_GrowerAccountListController.sortBy('',3,-1,accountList[0].Id);
                        Frontier_GrowerAccountListController.getAllGrowerAccounts(accountList[0].Name,3,1);
                        Frontier_GrowerAccountListController.getAllGrowerAccounts(accountList[0].Name,1,-1);
                        Frontier_GrowerAccountListController.sortByRADL('Develop',3,1);
                        Frontier_GrowerAccountListController.sortByRADL('',3,1);
                    }
                }
                catch(Exception le) {
                    System.debug('Message: ' + le.getMessage() + 'Cause: ' + le.getCause() + 'Line number: ' + le.getLineNumber() + 'Stack trace: ' + le.getStackTraceString());    
                }
                System.assert(!accountList.isEmpty(),'Accounts Created');
                Test.stopTest();
            }
        }
    }
}