src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated  Account Business Role</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Sales_Qty__c</fullName>
        <label>Net Sales Qty</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity for that particular crop for a particular year</description>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <description>Selling season for the Crop</description>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015 - Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 - Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2017 - Safra</fullName>
                </value>
                <value>
                    <fullName>2017 Safra</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Sales</label>
    <nameField>
        <label>Account Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Touchpoint__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TouchPoints (Account)</relationshipLabel>
        <relationshipName>TouchPoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <label>Check</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <formula>IF( ISPICKVAL(TouchPoint_Status__c, &quot;Completed&quot;) , NOW(), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TouchPoint_Status__c</fullName>
        <label>TouchPoint Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Not Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Touchpoint</label>
    <nameField>
        <label>TouchPoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TouchPoints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDashboardbyMonth.cls
public class TestDashboardbyMonth {
    
    @AuraEnabled
    public static void getbyMonth(){
        String crop = 'Corn';
        String season = '2016 Safra';
        List<Account_Sales__c> accSalesList = new List<Account_Sales__c>();
        Schema.DescribeFieldResult fieldResult;
        List<Schema.PicklistEntry> radlClass;   
        fieldResult = Account_Business_Role__c.Service_Level_Class_Descr__c.getDescribe();
        radlClass = fieldResult.getPicklistValues();
        Set<String> radlClassSet = new Set<String>();
        Set<Id> accCropSeasonId = new Set<Id>();
        List<TouchPoint__c> touchpointList= new List<TouchPoint__c>();
        List<Account_Business_Role__c> accbusinessList = new List<Account_Business_Role__c>();
        Map<Id,String> touchmonthMap = new Map<Id,String>();
        Map<Id,List<Id>> touchAccMap = new Map<Id,List<Id>>();
        RadlTouchWrapper radltouchwrapper; 
        RadlTouchcountWrapper radlwrapper;
        RadlTouchcountWrapper checkwrapper;
        
        if(!radlClass.isEmpty()){
            for(integer i=0;i<radlClass.Size();i++){
                radlClassSet.add(radlClass[i].getvalue());                        
            }
        }
        
        accSalesList = [SELECT Account_SFID__c,Net_Sales_Qty__c,Opportunity__c FROM Account_Sales__c WHERE Selling_Season_Descr__c = :season AND Crop__c = :crop AND Account_Business_Role_SFID__r.Role_Descr__c='Partner'];
        if(!accSalesList.isEmpty()){
            for(Account_Sales__c accSales : accSalesList){
                accCropSeasonId.add(accSales.Account_SFID__c);
                System.debug('accCropSeasonId' + accCropSeasonId);
            }
            
            touchpointList = [SELECT Id, Account_SFID__c, Account_SFID__r.Id, Check__c FROM TouchPoint__c WHERE TouchPoint_Status__c = 'Completed' AND Account_SFID__r.Id IN :accCropSeasonId];
            //touchpointList = Database.query(query);
            system.debug('touchpointList' +touchpointList.size() + ' '+touchpointList);
            if(!touchpointList.isEmpty()){
                System.debug('Inside touchpoint list');
                for(TouchPoint__c tPoint : touchpointList){
                    //touchmonthAccMap.put(tPoint.Account__r.Id,((tPoint.Completion_Date__c).format('MMMMM'))); 
                    if(tPoint.Check__c != null){
                        touchmonthMap.put(tPoint.Id,((tPoint.Check__c).format('MMMMM')));
                        if(touchAccMap.containsKey(tPoint.Account_SFID__c)){
                            List<Id> touchId = touchAccMap.get(tPoint.Account_SFID__c);
                            touchId.add(tPoint.Id);  
                            touchAccMap.put(tPoint.Account_SFID__c, touchId);  
                        }
                        else{
                            touchAccMap.put(tPoint.Account_SFID__c, new List<Id> {tPoint.Id});
                        }
                    }
                } 
                System.debug('touchmonthAccMap' + touchAccMap +' ' + touchmonthMap);
                System.debug('touchmonthMap'+ touchmonthMap);
            } 
            radltouchwrapper = new RadlTouchWrapper();
           // radlwrapper = new  RadlTouchcountWrapper();
            accbusinessList = [SELECT Id, Account_SFID__c, Service_Level_Class_Descr__c FROM Account_Business_Role__c WHERE Account_SFID__c = :touchAccMap.keySet() AND Role_Descr__c='Partner'];
            
            for(Account_Business_Role__c accbusiness : accbusinessList){
                //radltouchwrp = new  RADLtouchWrapper();
                    
                //checkwrapper = new  RadlTouchcountWrapper();
                if(radlClassSet.contains(accbusiness.Service_Level_Class_Descr__c)){
                    System.debug('accbusiness.Account_SFID__c' + accbusiness.Account_SFID__c);
                    if(!touchAccMap.isEmpty() && touchAccMap.containskey(accbusiness.Account_SFID__c)){
                        System.debug('Not empty');
                        List<Id> touchIdList = touchAccMap.get(accbusiness.Account_SFID__c);
                        for(Id tpId : touchIdList){
                            System.debug('Inside Touchpoint List' + tpId);
                            if(touchmonthMap.containskey(tpId) && radltouchwrapper.touchpermontcount.containskey(touchmonthMap.get(tpId))){
                               radlwrapper = radltouchwrapper.touchpermontcount.get(touchmonthMap.get(tpId));
                            }
                           else{
                              radlwrapper = new  RadlTouchcountWrapper();
                           }
                            
                          
                            if(touchmonthMap.containsKey(tpId)){
                                if(radltouchwrapper.touchpermontcount.containsKey((touchmonthMap.get(tpId)))){
                                    System.debug('Inside contains month');
                                    if((radltouchwrapper.touchpermontcount.get((touchmonthMap.get(tpId)))).radltouchcount.containsKey(accbusiness.Service_Level_Class_Descr__c)){
                                        System.debug('Inside contains radl in the month map');
                                        System.debug('radlwrapper.radltouchcount' + radlwrapper.radltouchcount);
                                        radlwrapper.radltouchcount.put(accbusiness.Service_Level_Class_Descr__c,(((radltouchwrapper.touchpermontcount.get((touchmonthMap.get(tpId)))).radltouchcount.get(accbusiness.Service_Level_Class_Descr__c))+1));
                                        
                                        radltouchwrapper.touchpermontcount.put((touchmonthMap.get(tpId)),radlwrapper);
                                        System.debug('Inside contains radl in the month map' + radltouchwrapper.touchpermontcount);
                                    } 
                                    else{
                                        System.debug('Inside not contains radl in the month map');
                                        //radlwrapper = new  RadlTouchcountWrapper();
                                        System.debug('radlwrapper' + radlwrapper.radltouchcount);
                                        Integer touchcount =1;
                                        radlwrapper.radltouchcount.put(accbusiness.Service_Level_Class_Descr__c,touchcount);
                                        radltouchwrapper.touchpermontcount.put((touchmonthMap.get(tpId)),radlwrapper);
                                        System.debug('Inside not contains radl in the month map' + radltouchwrapper.touchpermontcount);
                                    }
                                } 
                                else{
                                    System.debug('Inside not contains month');
                                    Integer touchcount = 1;
                                    System.debug('Inside not contains month init' + radltouchwrapper.touchpermontcount);
                                    radlwrapper.radltouchcount.put(accbusiness.Service_Level_Class_Descr__c,touchcount);
                                    radltouchwrapper.touchpermontcount.put((touchmonthMap.get(tpId)),radlwrapper);
                                    System.debug('Inside not contains month' + radltouchwrapper.touchpermontcount);
                                }
                            }
                        }
                        //radlwrp.radlcount.put(accbusiness.Service_Level_Class_Descr__c ,accountMap.get(accbusiness.Account_SFID__c));
                        //System.debug('radlwrp.radlcount' + radlwrp.radlcount);
                        //radltouchwrp.radltouchcount.put(touchmonthAccMap.get(accbusiness.Account_SFID__c),radlwrp);
                        //System.debug('radltouchwrp.radltouchcount' + radltouchwrp.radltouchcount);
                    }
                }   
            } 
            
            System.debug('radltouchwrapper.touchpermontcount' + radltouchwrapper.touchpermontcount);
           // System.debug('radltouchwrp.radltouchcount' + radltouchwrp.radltouchcount);
        }
    }
    public class RadlTouchWrapper{ 
        public Map<String,RadlTouchcountWrapper> touchpermontcount {get;set;}
        
        public RadlTouchWrapper(){
            touchpermontcount = new Map<String,RadlTouchcountWrapper>();
        }
    }
    
    public class RadlTouchcountWrapper{ 
        public Map<String,Integer> radltouchcount {get;set;}
        
        public RadlTouchcountWrapper(){
            radltouchcount = new Map<String,Integer>();
        }
    }
    
    
}