src/objects/Account_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Programs</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_SFID__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Program</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestReviewController.cls
public class TestReviewController {
@AuraEnabled
    public static List<Program__c> getPrograms(){
        List<Program__c> programList = new List<Program__c>();
        List<Account_Program__c> accPgmNewList = new List<Account_Program__c>();
        Map<Id,Id> pgmAccMap = new Map<Id,Id>();
        Set<Id> pgmIdSet = new Set<Id>();
        programList = [SELECT Id, Name FROM Program__c];
        if(programList.size()>0 && programList != null ){
            for(Program__c pgmIdList : programList){
                pgmIdSet.add(pgmIdList.Id);
        }
        }
        //String query = 'SELECT Id, Program__c, Account__c, Execution_Status__c FROM Account_Program__c Where Program__r.Id = :pgmIdSet';
        accPgmNewList = [SELECT Id, Program_SFID__c, Account_SFID__c, Execution_Status__c FROM Account_Program__c Where Program_SFID__r.Id = :pgmIdSet AND Execution_Status__c = 'New'];
        for(Account_Program__c accPgm : accPgmNewList){
          System.debug('Inside for');  
           pgmAccMap.put(accPgm.Program_SFID__c,accPgm.Account_SFID__c); 
        }
        return programList;
    }
}