src/objects/Account_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Programs</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planning_Status__c</fullName>
        <label>Planning Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Post-Plan</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Program</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planning_Status__c</fullName>
        <label>Planning Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Post-Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <label>Program</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Frontier_ProgramController_Test.cls
/* 
*
* @author : Cognizant technology solutions.
* @version : 1.0
* @objects Referenced :Account,Program,Account Program Object 
* @Description : This test class is covering code lines for apex class "Frontier_ProgramController"
*/


@isTest
public class Frontier_ProgramController_Test {

     @testSetup
    static void setup(){
        TestUtilClass.createTestUsers('System Administrator',2);
        TestUtilClass.createTestAccount(10);
       TestUtilClass.createTestGrowerAccount(10);
        TestUtilClass.createTestAccountRole(7);
        TestUtilClass.createTestProgram(4);
        TestUtilClass.createTestAccountProgram(7);
        TestUtilClass.createTestProduct(6);
        TestUtilClass.createTestAccountProduct(6);
        TestUtilClass.createTestTouchpoint(6);
        TestUtilClass.createTask(6);
        
        
        
        
    }
    static testmethod void getDetails() {
         User currentUser = new User();
        currentUser  = [SELECT Id FROM User Where Id =:UserInfo.getUserId()]; 
        if(currentUser != null){
            System.runAs(currentUser){
                list<account> accountList= new list<account>();
                list<Program__c> pgmList = new list<Program__c>();
                accountList=[SELECT Id,Name FROM Account LIMIT 10];
                pgmList = [SELECT id,Name FROM Program__c LIMIT 5];
                List<Account_Program__c> accPgmSalesList = [SELECT Id,CreatedBy.ID,Execution_Status__c FROM Account_Program__c WHERE CreatedBy.ID = :UserInfo.getUserId()];  
                system.debug('accPgmSalesList in Test Class' + accPgmSalesList); 
                Test.startTest(); 
                try{                                  
                    if(!accountList.isEmpty()){
                        
                        Frontier_ProgramController.getAllPrograms('null','false','10','5','true');
                        Frontier_ProgramController.getAllPrograms(accountList[0].id,'false','10','5','false');
                        Frontier_ProgramController.getAllPrograms('null','true','10','5','false');
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','null',true,false);

                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Service_Level_Class_Descr__c-ASC',false,false);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Account_SFID__r.Name-ASC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Planning_Status__c-ASC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Execution_Status__c-ASC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Location-ASC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Product_SFID__r.Name-ASC',false,true);
                        Frontier_ProgramController.getMyPrograms(pgmList[0].id,accountList[0].id,'false','true');
                        Frontier_ProgramController.getMyPrograms(pgmList[0].id,accountList[0].id,'true','false');
                        Frontier_ProgramController.getMyProgramAccounts(pgmList[0].id,'10','1','Service_Level_Class_Descr__c-ASC',false,false);
                        //Frontier_ProgramController.getCancelPgm('Not Started',accPgmSalesList[0].id,'Cancelled');
                        //Frontier_ProgramController.getCompletePgm('Not Started',accPgmSalesList[0].id);
                        Frontier_ProgramController.getSeasonData('SUMMER');

                        







                    }
                }
                 catch(Exception le) {
                    System.debug('Message: ' + le.getMessage() + 'Cause: ' + le.getCause() + 'Line number: ' + le.getLineNumber() + 'Stack trace: ' + le.getStackTraceString());    
                    
                }
                System.assert(!accountList.isEmpty(),'Accounts Created');
                
                Test.stopTest();
            }
        }
    }
    static testmethod void getTestDetails() {
         User currentUser = new User();
                       

        currentUser  = [SELECT Id FROM User Where Id =:UserInfo.getUserId()]; 
        if(currentUser != null){
            System.runAs(currentUser){
                list<account> accountList= new list<account>();
                list<Program__c> pgmList = new list<Program__c>();
                accountList=[SELECT Id,Name FROM Account LIMIT 10];
                pgmList = [SELECT id,Name FROM Program__c LIMIT 5];
                List<Account_Program__c> accPgmSalesList = [SELECT Id,CreatedBy.ID,Execution_Status__c FROM Account_Program__c WHERE CreatedBy.ID = :UserInfo.getUserId() AND Execution_Status__c = 'In Execution'];  
                system.debug('accPgmSalesList in Test Class' + accPgmSalesList[0].id); 
                Test.startTest(); 
                try{                                  
                    if(!accountList.isEmpty()){
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Service_Level_Class_Descr__c-DESC',false,false);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Account_SFID__r.Name-DESC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Planning_Status__c-DESC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Execution_Status__c-DESC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Location-DESC',false,true);
                        Frontier_ProgramController.getPgmAccounts(pgmList[0].id,'10','1','Product_SFID__r.Name-DESC',false,true);

                       Frontier_ProgramController.getMyProgramAccounts(pgmList[0].id,'10','1','Service_Level_Class_Descr__c-DESC',false,false);
                      Frontier_ProgramController.getCompletePgm('Completed',accPgmSalesList[0].id);
                         Frontier_ProgramController.getMyProgramsChart(pgmList[0].id,accountList[0].id,'false','true',true);
                         Frontier_ProgramController.getMyProgramsChart(pgmList[0].id,accountList[0].id,'false','false',true);

                       Frontier_ProgramController.getMyProgramsChart(pgmList[0].id,'null','true','false',false);

                       Frontier_ProgramController.getCancelPgm('Cancelled',null,'Cancelled');



                       
                    }
                }
                 catch(Exception le) {
                    System.debug('Message: ' + le.getMessage() + 'Cause: ' + le.getCause() + 'Line number: ' + le.getLineNumber() + 'Stack trace: ' + le.getStackTraceString());    
                    
                }
                System.assert(!accountList.isEmpty(),'Accounts Created');
                
                Test.stopTest();
            }
        }
    }
}