src/objects/Account_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Programs</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_SFID__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click on submitted button from program planning screen will check this field</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Program</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Allocated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consumed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Consumed</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <label>Program</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>1:1 Visit</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Growing</fullName>
                </value>
                <value>
                    <fullName>Harvest</fullName>
                </value>
                <value>
                    <fullName>Pre-Planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Activities (Program)</relationshipLabel>
        <relationshipName>Program_Activities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Not Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Touchpoint_Type__c</fullName>
        <label>Touchpoint Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1:1 Visit</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>E-Mail</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Activity</label>
    <nameField>
        <label>Program Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Frontier_AccountProgramClass.cls
public class Frontier_AccountProgramClass{
    public static Map<Id,Set<Id>> accountprogramMap;
    public static Set<Id> accountIds;
    public static List<Task> programActivityTasks = new List<Task>();
    // public static Set<Id> accountIds = new Set<Id>();
    // public static Set<Id> programIds = new Set<Id>();
    public static List<Program_Activity__c> programActivityList;
    public static Set<Id> completedProgramIds;
    public static void AssociateProgramActivities(List<Account_Program__c> accountPrograms,Map<Id,Account_Program__c> accountProgramOldMap,String triggerContext){
        accountprogramMap = new Map<Id,Set<Id>>();
        completedProgramIds = new Set<Id>();
        programActivityTasks = new List<Task>();
        accountIds = new Set<Id>();
        List<program__c> programList = new List<program__c>();
        for(Account_Program__c accountProgram : accountPrograms){
            if(!accountProgramOldMap.isEmpty() && ((triggerContext == 'isUpdate' && accountProgramOldMap.get(accountProgram.Id).Submitted__c != accountProgram.Submitted__c) || (triggerContext == 'isDelete')))
                if(accountProgram.Submitted__c){
                    if(!accountProgramMap.containsKey(accountProgram.Program_SFID__c)){
                        accountProgramMap.put(accountProgram.Program_SFID__c,new Set<Id>{accountProgram.Account_SFID__c});
                    }
                    else{
                        accountProgramMap.get(accountProgram.Program_SFID__c).add(accountProgram.Account_SFID__c);
                    }
                    accountIds.add(accountProgram.Account_SFID__c);
                 }                  

            else if(accountProgram.Execution_Status__c == 'Completed'){
                completedProgramIds.add(accountProgram.Program_SFID__c);
            }
        }
        
        if(triggerContext == 'isUpdate'){
            if(!accountProgramMap.isEmpty()){
                for(Program_Activity__c programActivity : [SELECT Id,Name,Phase__c,Activity_Type__c,Program_SFID__c,Status__c,Touchpoint_type__c FROM Program_Activity__c WHERE Program_SFID__c IN:accountProgramMap.keyset()]){
                    for(Id accId : accountProgramMap.get(programActivity.Program_SFID__c)){
                    programActivityTasks.add(new Task(Phase__c = programActivity.Phase__c,Status = 'Not Scheduled',Program_SFID__c = programActivity.Program_SFID__c,Type = programActivity.Activity_Type__c,
                                                      Subject = programActivity.Name,Program_Activity_SFID__c = programActivity.Id, WhatId = accId));
                    }                    
                }
                
            }
            programList = [SELECT Id,Allocated__c,Available__c,Consumed__c,Budget__c FROM Program__c];
            if(!programList.isEmpty()){
                
                for(program__c prog : programList){
                    if(!accountProgramMap.isEmpty() && accountProgramMap.containskey(prog.Id)){
                        prog.Allocated__c = (prog.Allocated__c == null ? 1 : prog.Allocated__c + 1);
                        prog.Budget__c =    (prog.Budget__c == null ? 0 : prog.Budget__c);
                        prog.Available__c =   prog.Available__c - prog.Allocated__c;
                        prog.Consumed__c = (prog.Consumed__c == null ? 0 : prog.Consumed__c);
                    }                    
                    else if(!completedProgramIds.isEmpty() && completedProgramIds.contains(prog.Id)){
                        prog.Allocated__c = ((prog.Allocated__c == null || prog.Allocated__c == 0) ? 0 :prog.Allocated__c - 1);
                        //prog.Budget__c =     (prog.Budget__c == null ? 0 : prog.Budget__c);
                        // prog.Available__c =  prog.Budget__c - prog.Allocated__c;
                        prog.Consumed__c = (prog.Consumed__c == null ? 0 : prog.Consumed__c);
                        prog.Consumed__c = prog.Consumed__c + 1;
                    }
                }
                
            }
        } 
        else if(triggerContext == 'isDelete'){
            Set<Id> programActivityIds = new Set<Id>();
            if(!accountProgramMap.isEmpty()){
                for(Program_Activity__c progActivity : [SELECT Id,Name,Phase__c,Program_SFID__c,Status__c FROM Program_Activity__c 
                                                        WHERE Program_SFID__c IN:accountProgramMap.keyset()]){
                                                            programActivityIds.add(progActivity.Id);
                                                        }
            }
            if(!programActivityIds.isEmpty()){
                programActivityTasks = [SELECT Id FROM Task WHERE Program_SFID__c IN:accountProgramMap.keyset() AND WhatId IN:accountIds
                                        AND Program_Activity_SFID__c IN:programActivityIds];
            }
            
            
            programList = [SELECT Id,Allocated__c,Available__c,Consumed__c,Budget__c FROM Program__c];
            if(!programList.isEmpty()){
                for(program__c prog : programList){
                    if(!accountProgramMap.isEmpty() && accountProgramMap.containsKey(prog.Id)){
                        prog.Allocated__c = ((prog.Allocated__c == null || prog.Allocated__c == 0) ? 0 :prog.Allocated__c - 1);
                        prog.Budget__c =     (prog.Budget__c == null ? 0 : prog.Budget__c);
                        prog.Available__c =  prog.Budget__c - prog.Allocated__c;
                        prog.Consumed__c = (prog.Consumed__c == null ? 1 : prog.Consumed__c);                        
                    }
                    else if(!completedProgramIds.isEmpty() && completedProgramIds.contains(prog.Id)){
                        prog.Consumed__c = (prog.Consumed__c == 0 ? 0 : prog.Consumed__c - 1);
                    }
                }
            }
        }
        
        
        if(!programActivityTasks.isEmpty()){ 
            try{
                if(triggerContext == 'isUpdate'){
                    insert programActivityTasks;
                }
                else if(triggerContext == 'isDelete'){
                    delete programActivityTasks;
                }
            }
            catch(Exception e){
                System.debug('Exception Occured on '+triggerContext+'with the following message'+e.getMessage());
            }
        }
        if(!programList.isEmpty()){
            try {
                update programList;
            }               
            catch(Exception e){
                System.debug('Exception Occured on updating the program with the following message'+e.getMessage());
            }
        }
    }
}