src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Archive_Date__c</fullName>
        <description>Holds the date when the record was last marked for Archival.</description>
        <inlineHelpText>Date Archive Indicator was set to &quot;Y&quot;.</inlineHelpText>
        <label>Archive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Communication__c.object
<CustomObject>
    <description>Link Accounts to their associated Addresses, Phone Numbers, Emails, etc..  Many-to-many relationship.</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</description>
        <inlineHelpText>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</inlineHelpText>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Communication</description>
        <inlineHelpText>Account related to the Communication</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Date__c</fullName>
        <description>Holds the date when the record was last marked for Archival.</description>
        <inlineHelpText>Date Archive Indicator was set to &quot;Y&quot;.</inlineHelpText>
        <label>Archive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Name__c</fullName>
        <description>City Name</description>
        <inlineHelpText>City Name</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Addr__c</fullName>
        <description>Email Address</description>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Geocode__c</fullName>
        <description>Longitude/Latitude of an Address</description>
        <inlineHelpText>Longitude/Latitude of an Address</inlineHelpText>
        <label>Geocode</label>
        <scale>9</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Address/Phone/Email/etc. related to the Account Communication Role</description>
        <inlineHelpText>Account Address/Phone/Email/etc. related to the Account Communication Role</inlineHelpText>
        <label>Parent Account Communication</label>
        <referenceTo>Account_Communication__c</referenceTo>
        <relationshipLabel>Account Communication</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Extension_Number__c</fullName>
        <description>Phone Extension - For individuals/businesses that have an internal phone system, the additional numbers dialed once the internal system is connected to from the outside (Phone Number).</description>
        <inlineHelpText>Phone Extension - For individuals/businesses that have an internal phone system, the additional numbers dialed once the internal system is connected to from the outside (Phone Number).</inlineHelpText>
        <label>Extension</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Phone Number</description>
        <inlineHelpText>Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code</description>
        <inlineHelpText>Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Name__c</fullName>
        <description>State Name</description>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Addr__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>has_Do_Not_Call_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked indicates that the Contact has requested to not be called.</description>
        <inlineHelpText>Checked indicates that the Contact has requested to not be called.</inlineHelpText>
        <label>Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>has_Do_Not_Email_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked indicates that the Account has requested to not be emailed by Monsanto.</description>
        <inlineHelpText>Checked indicates that the Account has requested to not be emailed by Monsanto.</inlineHelpText>
        <label>Do Not Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Fax__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can Faxes be send to this Phone Number?</description>
        <inlineHelpText>Can Faxes be send to this Phone Number?</inlineHelpText>
        <label>Fax</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Communication</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Account Communication Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Communications</pluralLabel>
    <recordTypes>
        <fullName>Account_Communication_Address_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for physical address&apos; role&apos;s Business Role.</description>
        <label>Address Role Business Role</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Communication_Email_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for email address&apos;s role&apos;s Business Role.</description>
        <label>Email Role Business Role</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Communication_Phone_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for phone number&apos;s role&apos;s Business Role.</description>
        <label>Phone Role Business Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Archive_Date__c</fullName>
        <description>Holds the date when the record was last marked for Archival.</description>
        <inlineHelpText>Date the Archive Indicator was set to &quot;Y&quot;.</inlineHelpText>
        <label>Archive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; Indicates that the record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Communication__c.object
<CustomObject>
    <description>Link Contacts to their associated Addresses, Phone Numbers, Emails, etc..  Many-to-many relationship.</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Role Lookup associated with the Contact&apos;s Address/Phone/Email/etc.</description>
        <inlineHelpText>Business Role Lookup associated with the Contact&apos;s Address/Phone/Email/etc.</inlineHelpText>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Contact Communications</relationshipLabel>
        <relationshipName>Contact_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Archive_Date__c</fullName>
        <description>Holds the date when the record was last marked for Archival.</description>
        <inlineHelpText>Date Archive Indicator was set to &quot;Y&quot;.</inlineHelpText>
        <label>Archive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Name__c</fullName>
        <description>City Name</description>
        <inlineHelpText>City Name</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_SFID__c</fullName>
        <description>Contact related to the Communication</description>
        <inlineHelpText>Contact related to the Communication</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Communications</relationshipLabel>
        <relationshipName>Contact_Communications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Addr__c</fullName>
        <description>Email Address</description>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Geocode__c</fullName>
        <description>Longitude/Latitude of an Address</description>
        <inlineHelpText>Longitude/Latitude of an Address</inlineHelpText>
        <label>Geocode</label>
        <scale>9</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Address/Phone/Email/etc. related to the Account Communication Role</description>
        <inlineHelpText>Contact Address/Phone/Email/etc. related to the Account Communication Role</inlineHelpText>
        <label>Parent Contact Communication</label>
        <referenceTo>Contact_Communication__c</referenceTo>
        <relationshipLabel>Contact Communications</relationshipLabel>
        <relationshipName>Contact_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Extension_Number__c</fullName>
        <description>Phone Extension - For individuals/businesses that have an internal phone system, the additional numbers dialed once the internal system is connected to from the outside (Phone Number).</description>
        <inlineHelpText>Phone Extension - For individuals/businesses that have an internal phone system, the additional numbers dialed once the internal system is connected to from the outside (Phone Number).</inlineHelpText>
        <label>Extension</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Phone Number</description>
        <inlineHelpText>Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code</description>
        <inlineHelpText>Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Name__c</fullName>
        <description>State Name</description>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Addr__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>has_Do_Not_Call_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked indicates that the Contact has requested to not be called.</description>
        <inlineHelpText>Checked indicates that the Contact has requested to not be called.</inlineHelpText>
        <label>Do not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>has_Do_Not_Email_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked indicates that the Contact has requested to not be emailed by Monsanto</description>
        <inlineHelpText>Checked indicates that the Contact has requested to not be emailed by Monsanto</inlineHelpText>
        <label>Do Not Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Fax__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can Faxes be send to this Phone Number?</description>
        <inlineHelpText>Can Faxes be send to this Phone Number?</inlineHelpText>
        <label>Fax</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Communication</label>
    <nameField>
        <displayFormat>CC-{0}</displayFormat>
        <label>Contact Communication Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Communications</pluralLabel>
    <recordTypes>
        <fullName>Contact_Communication_Address_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for physical address&apos; role&apos;s Business Role.</description>
        <label>Address Role Business Role</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact_Communication_Email_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for email address&apos;s role&apos;s Business Role.</description>
        <label>Email Role Business Role</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact_Communication_Phone_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for phone number&apos;s role&apos;s Business Role.</description>
        <label>Phone Role Business Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Frontier_Gen_Communication_Controller.cls
public with sharing class Frontier_Gen_Communication_Controller { 
    
    @AuraEnabled 
    public static String getCommunicationDetails(Id recordId)
    {   
        String communicationDetails;
        //Verify current context is Account or Contact
        If(Schema.Account.SObjectType == recordId.getSobjectType())
        {
            // Call Account Communication Details method.
            communicationDetails = getAccCommunicationDetails(recordId);
            
        }else If(Schema.Contact.SObjectType == recordId.getSobjectType())
        {
            // Call Account Communication Details method.
            communicationDetails = getConCommunicationDetails(recordId);    		
        }
        System.debug('Communication Details'+communicationDetails);
        return communicationDetails; 
    }
    //This method retrives Account Communication Details
    @AuraEnabled 
    public static String getAccCommunicationDetails (Id recordId)
    {
        Id accountId = recordId;
        Account accountRecord = [SELECT Id, Name From Account Where Id =: accountId];
        List<Account_Communication__c> comAddress = new List<Account_Communication__c>();
        List<Account_Communication__c> comPhone = new List<Account_Communication__c>();
        List<Account_Communication__c> comEmail = new List<Account_Communication__c>();
        
            comAddress = [SELECT Id, Account_SFID__c, State_Name__c, Street_Addr__c, City_Name__c, Postal_Code__c FROM Account_Communication__c 
                          WHERE RecordType.DeveloperName = 'Account_Communication_Address_Role_Business_Role'
                        	AND Archive_Ind__c = 'N'
                        	AND Parent_SFID__r.Archive_Ind__c = 'N' 
                        	AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N'
                          	AND Account_SFID__c =: accountId];
            
            comPhone = [SELECT Id, Account_SFID__c, State_Name__c, Parent_SFID__c,Parent_SFID__r.Parent_SFID__r.Email_Addr__c ,Parent_SFID__r.Parent_SFID__r.Phone_Number__c, Phone_Extension_Number__c, Phone_Number__c, Street_Addr__c, City_Name__c, Postal_Code__c FROM Account_Communication__c 
                        WHERE RecordType.DeveloperName = 'Account_Communication_Phone_Role_Business_Role'
                        AND Archive_Ind__c = 'N'
                        AND Parent_SFID__r.Archive_Ind__c = 'N' 
                        AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N'
                        AND Account_SFID__c =: accountId];
            
            comEmail = [SELECT Id, Account_SFID__c, State_Name__c,Parent_SFID__c,Parent_SFID__r.Parent_SFID__r.Email_Addr__c ,Parent_SFID__r.Parent_SFID__r.Phone_Number__c,has_Do_Not_Email_Ind__c,Email_Addr__c, Street_Addr__c, City_Name__c, Postal_Code__c FROM Account_Communication__c 
                        WHERE RecordType.DeveloperName = 'Account_Communication_Email_Role_Business_Role'
                        AND Archive_Ind__c = 'N'
                        AND Parent_SFID__r.Archive_Ind__c = 'N' 
                        AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N'
                        AND Account_SFID__c =: accountId];
        
        CommunicationDataWrapper communicationData = new CommunicationDataWrapper();
        communicationData.commAddress = !comAddress.isEmpty() ?(String.valueOf(comAddress[0].Street_Addr__c) != null ? String.valueOf(comAddress[0].Street_Addr__c) : '')+ ', ' +
            (String.valueOf(comAddress[0].City_Name__c) != null ? String.valueOf(comAddress[0].City_Name__c) : '')+ ', ' +
            (String.valueOf(comAddress[0].State_Name__c) != null ? String.valueOf(comAddress[0].State_Name__c) : '')+'.' :'';
        
        communicationData.commPhone = !comPhone.isEmpty() ? String.valueOf(comPhone[0].Parent_SFID__r) != null ? 
            String.valueOf(comPhone[0].Parent_SFID__r.Parent_SFID__r) != null ? 
            String.valueOf(comPhone[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) != null ? 
            String.valueOf(comPhone[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) :'':'':'':'';
        
        communicationData.commEmail = !comEmail.isEmpty() ? String.valueOf(comEmail[0].Parent_SFID__r)	 != null ? 
            String.valueOf(comEmail[0].Parent_SFID__r.Parent_SFID__r) != null ? 
            String.valueOf(comEmail[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) != null ? 
            String.valueOf(comEmail[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) :'':'':'':'';
        
        communicationData.recordName = accountRecord.Name;
        
        communicationData.objectRecordType = 'Dealer Account';
        
        return JSON.serialize(communicationData);
    }
    
    @AuraEnabled 
    public static String getConCommunicationDetails(Id recordId)
    {
        Id contactId = recordId;
        System.debug('Received contactId'+contactId);
        
        Contact contactDetails = new Contact();
        List<Contact_Communication__c> contactAddress = new List<Contact_Communication__c>();
        List<Contact_Communication__c> contactPhone = new List<Contact_Communication__c>();
        List<Contact_Communication__c> contactEmail = new List<Contact_Communication__c>();
        
        if(contactId != null){            
            List<UserRecordAccess> lstUserRecordAccess;
            lstUserRecordAccess = [SELECT RecordId,MaxAccessLevel,HasAllAccess, 
                                   HasDeleteAccess, 
                                   HasEditAccess,
                                   HasReadAccess, 
                                   HasTransferAccess 
                                   FROM UserRecordAccess 
                                   WHERE UserId =: UserInfo.getUserId()
                                   AND RecordId =: contactId];
            ContactShare contactRecordShare = new ContactShare();
            if(lstUserRecordAccess[0].HasReadAccess == False)
            {
                contactRecordShare.ContactId = contactId;
                contactRecordShare.UserOrGroupId = UserInfo.getUserId();
                contactRecordShare.ContactAccessLevel = 'Read';
                contactRecordShare.RowCause = Schema.ContactShare.RowCause.Manual;
                insert contactRecordShare;    
            }
            contactDetails = [SELECT Id, FirstName, LastName, Name, MobilePhone, Email, MailingStreet, MailingCity, MailingState,
                         	 MailingCountry FROM Contact WHERE Id = : contactId];
            
            contactAddress= [SELECT Id, Account_Business_Role_SFID__c, Archive_Date__c, Archive_Ind__c, City_Name__c, Contact_SFID__c,
                             Country_Name__c, has_Do_Not_Call_Ind__c, has_Do_Not_Email_Ind__c, Email_Addr__c, Phone_Extension_Number__c, 
                             is_Fax__c, Geocode__c, HC_Integration_Key__c, is_Mobile_Phone__c, Parent_SFID__c, Parent_SFID__r.Email_Addr__c ,Parent_SFID__r.Phone_Number__c, Phone_Number__c, Postal_Code__c,
                             is_Primary_Communication__c, Role_Descr__c, State_Name__c, Street_Addr__c, is_Voice_Phone__c
                             FROM Contact_Communication__c 
                             WHERE   RecordType.DeveloperName = 'Contact_Communication_Address_Role_Business_Role'
                             AND Archive_Ind__c = 'N'
                             AND Parent_SFID__r.Archive_Ind__c = 'N' 
                             AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N'
                             AND Contact_SFID__c =: contactId];
            
            contactPhone= [SELECT Id, Account_Business_Role_SFID__c, Archive_Date__c, Archive_Ind__c, City_Name__c, Contact_SFID__c,
                           Country_Name__c, has_Do_Not_Call_Ind__c, has_Do_Not_Email_Ind__c, Email_Addr__c, Phone_Extension_Number__c, 
                           is_Fax__c, Geocode__c, HC_Integration_Key__c, is_Mobile_Phone__c, Parent_SFID__c,Parent_SFID__r.Parent_SFID__r.Email_Addr__c ,Parent_SFID__r.Parent_SFID__r.Phone_Number__c,Phone_Number__c, Postal_Code__c,
                           is_Primary_Communication__c,  Role_Descr__c, State_Name__c, Street_Addr__c, is_Voice_Phone__c
                           From Contact_Communication__c 
                           WHERE   RecordType.DeveloperName = 'Contact_Communication_Phone_Role_Business_Role'
                           AND Archive_Ind__c = 'N'
                           AND Parent_SFID__r.Archive_Ind__c = 'N' 
                           AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N'
                           AND Contact_SFID__c =: contactId];
            
            contactEmail= [SELECT Id, Account_Business_Role_SFID__c, Archive_Date__c, Archive_Ind__c, City_Name__c, Contact_SFID__c,
                           Country_Name__c, has_Do_Not_Call_Ind__c, has_Do_Not_Email_Ind__c, Email_Addr__c, Phone_Extension_Number__c, 
                           is_Fax__c, Geocode__c, HC_Integration_Key__c, is_Mobile_Phone__c, Parent_SFID__c, Parent_SFID__r.Parent_SFID__r.Email_Addr__c ,Parent_SFID__r.Parent_SFID__r.Phone_Number__c, Phone_Number__c, Postal_Code__c,
                           is_Primary_Communication__c, Parent_SFID__r.Archive_Ind__c, Parent_SFID__r.Parent_SFID__r.Archive_Ind__c, Role_Descr__c, State_Name__c, Street_Addr__c, is_Voice_Phone__c
                           From Contact_Communication__c 
                           WHERE   RecordType.DeveloperName = 'Contact_Communication_Email_Role_Business_Role'
                           AND Archive_Ind__c = 'N'AND Parent_SFID__r.Archive_Ind__c = 'N' 
                           AND Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = 'N' AND Contact_SFID__c =: contactId];
        }
        CommunicationDataWrapper communicationData = new CommunicationDataWrapper();
        communicationData.commAddress = !contactAddress.isEmpty() ?(String.valueOf(contactAddress[0].Street_Addr__c) != null ? String.valueOf(contactAddress[0].Street_Addr__c) : '')+ ', ' +
            (String.valueOf(contactAddress[0].City_Name__c) != null ? String.valueOf(contactAddress[0].City_Name__c) : '')+ ', ' +
            (String.valueOf(contactAddress[0].State_Name__c) != null ? String.valueOf(contactAddress[0].State_Name__c) : '')+'.' :'';
        
        communicationData.commPhone = !contactPhone.isEmpty() ? String.valueOf(contactPhone[0].Parent_SFID__r) != null ? 
            String.valueOf(contactPhone[0].Parent_SFID__r.Parent_SFID__r) != null ? 
            String.valueOf(contactPhone[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) != null ? 
            String.valueOf(contactPhone[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) :'':'':'':'';
        
        communicationData.commEmail = !contactEmail.isEmpty() ? String.valueOf(contactEmail[0].Parent_SFID__r) != null ? 
            String.valueOf(contactEmail[0].Parent_SFID__r.Parent_SFID__r) != null ? 
            String.valueOf(contactEmail[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) != null ? 
            String.valueOf(contactEmail[0].Parent_SFID__r.Parent_SFID__r.Phone_Number__c) :'':'':'':'';
        
        communicationData.recordName = contactDetails.Name;
        
        communicationData.objectRecordType = 'Contact';
        
        return JSON.serialize(communicationData);
        }
        
        class CommunicationDataWrapper{
            public String commAddress {get;set;}
            public String commPhone {get;set;}
            public String commEmail {get;set;}
            public String recordName {get;set;}
            public String objectRecordType {get;set;}
        }
        
    }