src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Descr__c</fullName>
        <description>Busines Unit/Line of Business associated with the Role.  Not all areas will have need to call out a specific line of business.  Example: &quot;Ag Chem&quot;, &quot;National&quot;, &quot;Channel&quot;, etc.</description>
        <inlineHelpText>Busines Unit/Line of Business associated with the Role.</inlineHelpText>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Seed and Traits</fullName>
                </value>
                <value>
                    <fullName>Agroceres</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Category_Descr__c</fullName>
        <description>Company level description of an Account&apos;s relationship to Monsanto.  Terminiology to be determined by Monsanto Global business.  For example, they may use the term &quot;Partner&quot; to represent an account that is the intermediary between Monsanto and the end consumer regardless of the specific business model.

Per discussion with Tony Rizzo, recommend to stick with ACS terminology of &quot;Partner&quot; and &quot;Customer&quot;.</description>
        <inlineHelpText>Company high level description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
                <value>
                    <fullName>Intermediary</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Programs</relationshipLabel>
        <relationshipName>Account_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planning_Status__c</fullName>
        <label>Planning Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Post-Plan</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click on submitted button from program planning screen will check this field</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Program</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>Account Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated  Account Business Role</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Descr__c</fullName>
        <description>This field is to describe the brand family.</description>
        <inlineHelpText>This field is to describe the brand family.</inlineHelpText>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>BioAg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Sales_Qty__c</fullName>
        <label>Net Sales Qty</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <description>Selling season for the Crop</description>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015 - Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 - Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2017 - Safra</fullName>
                </value>
                <value>
                    <fullName>2017 Safra</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dollars</fullName>
                </value>
                <value>
                    <fullName>Units</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Type__c</fullName>
        <label>Year Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fiscal Year</fullName>
                </value>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Crop Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Account Sales</label>
    <nameField>
        <label>Account Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Frontier_Gen_AccountSales_Controller.cls
public with sharing class Frontier_Gen_AccountSales_Controller { 
    
    @AuraEnabled
    public static String updateCYTarget(String CYTarget)
    {
        System.debug('received value');
        return 'Success';
    }
    
    @AuraEnabled 
    public static String getAccountSalesDetails(Id recordId, String accountType)
    {   
        String accountSalesDetails;
        if(accountType == 'Dealer')
        {
        	accountSalesDetails = getDealerAccountDetails(recordId, accountType);    
        }        
        System.debug('accountSalesDetails'+accountSalesDetails);
        return accountSalesDetails; 
    }
    //This method retrives Account Communication Details
    @AuraEnabled 
    public static String getDealerAccountDetails (Id recordId, String accountType)
    {        
        Id accountId = recordId;
        Account accountRecord = [SELECT Id, Name From Account Where Id =: accountId];
        Integer currentYear = System.Today().year();
        List<Account_Sales__c> accSales = new List<Account_Sales__c>();
        accSales = [SELECT Id, Name, Account_SFID__c, Account_Business_Role_SFID__c, Brand_Name__c, Business_Unit_Descr__c,
                   Crop__c, Net_Sales_Qty__c, Selling_Season_Descr__c, Unit_Of_Measure__c, Year__c, Year_Type__c
                   From Account_Sales__c 
                   Where Account_SFID__c =: accountId 
                   AND Selling_Season_Descr__c = 'SUMMER'
                   AND Account_Business_Role_SFID__r.Role_Descr__c = 'Partner'
                   AND Account_Business_Role_SFID__r.Role_Category_Descr__c = 'Intermediary'];
        
        map<Id, Double> mapCYSales = new map<Id, Double>();
        map<Id, Double> mapPYSales = new map<Id, Double>();    
        map<Id, Double> map2PYSales = new map<Id, Double>();
        
        for(Account_Sales__c acSal : accSales)
        {
            if(acSal.Selling_Season_Descr__c != null && acSal.Selling_Season_Descr__c == 'SUMMER')
            {
                if(acSal.Year__c == String.valueOf(currentYear))
                {
                    if(!mapCYSales.containsKey(acSal.Id))
                    {
                        mapCYSales.put(acSal.Id, acSal.Net_Sales_Qty__c);
                    }else if(mapCYSales.containsKey(acSal.Id))
                    {
                        mapCYSales.put(acSal.Id, mapCYSales.get(acSal.Id)+acSal.Net_Sales_Qty__c);
                    }
                    System.debug('mapCYSales'+mapCYSales.values());
                }
                if(acSal.Year__c == String.valueOf(currentYear - 1))
                {
                    if(!mapPYSales.containsKey(acSal.Id))
                    {
                        mapPYSales.put(acSal.Id, acSal.Net_Sales_Qty__c);
                    }else if(mapPYSales.containsKey(acSal.Id))
                    {
                        mapPYSales.put(acSal.Id, mapPYSales.get(acSal.Id)+acSal.Net_Sales_Qty__c);
                    }
                    System.debug('mapPYSales'+mapPYSales.values());
                }
                if(acSal.Year__c == String.valueOf(currentYear - 2))
                {
                    if(!map2PYSales.containsKey(acSal.Id))
                    {
                        map2PYSales.put(acSal.Id, acSal.Net_Sales_Qty__c);
                    }else if(map2PYSales.containsKey(acSal.Id))
                    {
                        map2PYSales.put(acSal.Id, map2PYSales.get(acSal.Id)+acSal.Net_Sales_Qty__c);
                    }
                    System.debug('map2PYSales'+map2PYSales.values());
                }
            }
        }
        
        List<Account_Program__c> accPrograms = new List<Account_Program__c>();
        accPrograms = [Select Id, Name, Account_SFID__c, Planning_Status__c, Execution_Status__c, Submitted__c, Service_Level_Class_Descr__c 
                       From Account_Program__c where Account_SFID__c =: accountId Limit 1];
        
        AccountSalesDataWrapper accountSalesData = new AccountSalesDataWrapper();
        accountSalesData.CYSales = String.valueOf(mapCYSales.values()) != null ? String.valueOf(mapCYSales.values()) : 'NA';
        accountSalesData.PYSales = String.valueOf(mapPYSales.values()) != null ? String.valueOf(mapPYSales.values()) : 'NA';
        accountSalesData.twoPYSales = String.valueOf(map2PYSales.values()) != null ? String.valueOf(map2PYSales.values()) : 'NA';
        accountSalesData.AccountStatus = !accPrograms.isEmpty() ? accPrograms[0].Planning_Status__c != null ? accPrograms[0].Planning_Status__c : '' : 'Not Planned';
        
        return JSON.serialize(accountSalesData);
    }
        class AccountSalesDataWrapper{
            public String CYSales {get;set;}
            public String PYSales {get;set;}
            public String twoPYSales {get;set;}
            public String AccountStatus {get;set;}
        }        
    }