src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Farming_Area__c.object
<CustomObject>
    <description>This object is to store the historical and current farming area data</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>to describe whether it&apos;s a Grower/Dealer</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account to which the Farming area is referring to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Area_Opportunity__c</fullName>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area_Usage_Descr__c</fullName>
        <label>Agricultural Usage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa/Lucerne</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017 Safra</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2017 Safrinha</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Sarfrinha</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safrinha</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
                <value>
                    <fullName>SPRING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Farming Area</label>
    <nameField>
        <label>Account Farming Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Farming Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated  Account Business Role</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Sales_Qty__c</fullName>
        <label>Net Sales Qty</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity for that particular crop for a particular year</description>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <description>Selling season for the Crop</description>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015 - Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 - Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2017 - Safra</fullName>
                </value>
                <value>
                    <fullName>2017 Safra</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Sales</label>
    <nameField>
        <label>Account Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Role Lookup associated with the Account&apos;s Visit</description>
        <inlineHelpText>Business Role Lookup associated with the Account&apos;s Visit</inlineHelpText>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TouchPoint_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TouchPoint</label>
        <referenceTo>Touchpoint__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>TouchPoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Touchpoint__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TouchPoints (Account)</relationshipLabel>
        <relationshipName>TouchPoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <label>Check</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <formula>IF( ISPICKVAL(TouchPoint_Status__c, &quot;Completed&quot;) , NOW(), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TouchPoint_Status__c</fullName>
        <label>TouchPoint Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Not Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Touchpoint</label>
    <nameField>
        <label>TouchPoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TouchPoints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountDashboard.cls
public class TestAccountDashboard {
    
    @AuraEnabled
    public static String getDealersList(Integer pageNumber,Integer pageSize,String crop, String season, String accType){ 
		System.debug('crop'+crop);
        System.debug('season'+season);
        List<Account_Business_Role__c> accpgmRadl =  new List<Account_Business_Role__c>();
        List<Account_Business_Role__c> accbussinessRoleList =  new List<Account_Business_Role__c>();
        List<Touchpoint__c> touchpointList = new List<Touchpoint__c>();
        List<Account> accountList = new List<Account>();
        List<Account_Farming_Area__c> accFarmingList= new List<Account_Farming_Area__c>();
        List<Account_Sales__c> accSalesList= new List<Account_Sales__c>();
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> accCropSeasonId = new Set<Id>();
        Map<Id,Integer> accTouchpointMap = new Map<Id,Integer>();
        Map<Id,DateTime> accTouchpointDateMap = new Map<Id,DateTime>();
        Integer noOfRecordsToSkip=(Integer.valueOf(pageNumber)-1)*Integer.valueOf(pageSize);
        //Get accounts having selected season and crop
        if(accType == 'Customer'){
          accFarmingList = [SELECT Account_SFID__c,Area_Opportunity__c FROM Account_Farming_Area__c WHERE Selling_Season_Descr__c = :season AND Area_Usage_Descr__c = :crop AND Account_Business_Role_SFID__r.Role_Descr__c='Customer'];
        	//accSalesList = [SELECT Account_SFID__c,Net_Sales_Qty__c FROM Account_Sales__c WHERE Selling_Season_Descr__c = :season AND Area_Usage_Descr__c = :crop AND Account_Business_Role_SFID__r.Role_Descr__c='Customer'];
            // accountList = [Select Id,(SELECT Id, Account_SFID__c, Account_SFID__r.Id, Completion_Date__c,Check__c FROM TouchPoints__r WHERE TouchPoint_Status__c = 'Completed') FROM Account WHERE Id IN (SELECT Account_SFID__c FROM Account_Farming_Area__c WHERE Selling_Season_Descr__c = :season AND Area_Usage_Descr__c = :crop AND Account_Business_Role_SFID__r.Role_Descr__c='Customer')];
         if(!accFarmingList.isEmpty()){
            for(Account_Farming_Area__c accFarming : accFarmingList){
                accCropSeasonId.add(accFarming.Account_SFID__c);
                System.debug('accCropSeasonId' + accCropSeasonId);
            }
        }
        }
        if(accType == 'Partner'){
          accSalesList = [SELECT Account_SFID__c,Net_Sales_Qty__c,Opportunity__c FROM Account_Sales__c WHERE Selling_Season_Descr__c = :season AND Crop__c = :crop AND Account_Business_Role_SFID__r.Role_Descr__c='Partner'];
          if(!accSalesList.isEmpty()){
            for(Account_Sales__c accSales : accSalesList){
                accCropSeasonId.add(accSales.Account_SFID__c);
                System.debug('accCropSeasonId' + accCropSeasonId);
            }
        }
        } 
        accpgmRadl = [SELECT Id, Service_Level_Class_Descr__c ,Account_SFID__c,Account_SFID__r.Name FROM Account_Business_Role__c WHERE Service_Level_Class_Descr__c != null AND Account_SFID__c IN :accCropSeasonId AND Role_Descr__c='Partner'];
        if(!accpgmRadl.isEmpty()){
            for(Integer i = noOfRecordsToSkip; i < noOfRecordsToSkip + Integer.valueOf(pageSize) && i < accpgmRadl.size();i++){
                if(!accountIdSet.contains(accpgmRadl[i].Account_SFID__C)){
                    accountIdSet.add(accpgmRadl[i].Account_SFID__C); 
                }
                accbussinessRoleList.add(accpgmRadl[i]);                 
            }
        }
        set<DateTime> completionDateSet = new set<DateTime>();
        if(!accountIdSet.isEmpty()){
            accountList = [SELECT Id,Name,(Select Id,Completion_Date__c From TouchPoints__r WHERE TouchPoint_Status__c = 'Completed' AND TouchPointTypes__c ='1:1 Visit' AND Completion_Date__c = THIS_YEAR) FROM Account Where Id =:accountIdSet];
            for(Account account : accountList ){
                if(!account.TouchPoints__r.isEmpty()){
                    accTouchpointMap.put(account.Id,account.TouchPoints__r.size());
                    
                }
            }
            for(Account account : [SELECT Id,Name,(Select Id,Completion_Date__c From TouchPoints__r WHERE TouchPoint_Status__c = 'Completed' AND TouchPointTypes__c ='1:1 Visit' AND Completion_Date__c = THIS_YEAR ORDER BY Completion_Date__c DESC LIMIT 1) FROM Account Where Id =:accountIdSet ]){
            if(!account.TouchPoints__r.isEmpty()){
                    accTouchpointDateMap.put(account.Id,account.TouchPoints__r[0].Completion_Date__c);
            }
            }
        }
        List<DealerWrapper> dealerWrapperList = new List<DealerWrapper>();
        if(!accbussinessRoleList.isEmpty()){
            for(Account_Business_Role__c accbussrole:accbussinessRoleList){
                DealerWrapper dealerWrapperdetails = new DealerWrapper();
                dealerWrapperdetails.accountName = accbussrole.Account_SFID__r.Name;
                dealerWrapperdetails.accountRADL = accbussrole.Service_Level_Class_Descr__c; 
                dealerWrapperdetails.Count =  (accpgmRadl.size() > 0 ? accpgmRadl.size(): 0);
                if(!accTouchpointMap.isEmpty() && accTouchpointMap.containskey(accbussrole.Account_SFID__c)){
                    dealerWrapperdetails.accTouchpointCount =accTouchpointMap.get(accbussrole.Account_SFID__c);
                } 
                else{
                    dealerWrapperdetails.accTouchpointCount =0;
                }
                if(!accTouchpointDateMap.isEmpty() && accTouchpointDateMap.containskey(accbussrole.Account_SFID__c)){
                    dealerWrapperdetails.accTouchpointDate =accTouchpointDateMap.get(accbussrole.Account_SFID__c);
                } 
                dealerWrapperList.add(dealerWrapperdetails);
                
            } 
            
        }
        else{
            dealerWrapperList = new List<DealerWrapper>();
            
        }
        return JSON.serialize(dealerWrapperList);
        
    }   
    
    public class DealerWrapper{ 
        public Integer Count {get;set;}
        public String accountName {get;set;}
        public String accountRADL {get;set;}
        public Integer accTouchpointCount {get;set;}
        public DateTime accTouchpointDate {get;set;}

        
        
        public DealerWrapper(){
            
        }
    }
}