src/objects/Account_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Associated Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account_Sales</relationshipLabel>
        <relationshipName>Account_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Sales_Qty__c</fullName>
        <label>Net Sales Qty</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity for that particular crop for a particular year</description>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Qty__c</fullName>
        <label>Order Qty</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Account Sales</label>
    <nameField>
        <label>Account Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Frontier_DealerOpportunityChart.cls
public class Frontier_DealerOpportunityChart {
	@AuraEnabled    
    public static String getdealerOpportunity(Id dealerAccId){
        System.debug('Inside apex');
        List<Account_Sales__c> accSalesList = new List<Account_Sales__c>();
        AccountDataWrapper accountData = new AccountDataWrapper();
        //Set<String> seasonSet = new Set<String>{'2017 Safra','2016 Safra','2015 Safra'};
        String Crop = 'Corn';
        String queryString= 'Select Id,Name,Account_SFID__c,Net_Sales_Qty__c,Year__c,Order_Qty__c,Budget__c,Opportunity__c From Account_Sales__c where Account_SFID__c=:dealerAccId AND Crop__c=:crop';  
        accSalesList =Database.query(queryString);
        System.debug('accSalesList' + accSalesList);
        if(!accSalesList.isEmpty()){
        for(Account_Sales__c accSales :accSalesList){
          accountData.SalesYearMap.put(accSales.Year__c,accSales.Net_Sales_Qty__c) ;
          accountData.OpportunityYearMap.put(accSales.Year__c,accSales.Opportunity__c) ;
          accountData.BudgetYearMap.put(accSales.Year__c,accSales.Budget__c) ;
        }
        }
        System.debug('SalesYearMap' +accountData.SalesYearMap +accountData.OpportunityYearMap);
        return JSON.serialize(accountData);
        
        
    }
    
     public class AccountDataWrapper{
        public  Map<String,Decimal> SalesYearMap{get;set;}
        public  Map<String,Decimal> OpportunityYearMap{get;set;}
        public Map<String,Decimal> BudgetYearMap{get;set;}
         public AccountDataWrapper(){
            SalesYearMap=new Map<String,Decimal>();
            OpportunityYearMap=new Map<String,Decimal>();
             BudgetYearMap=new Map<String,Decimal>();
        }
     }
}