src/objects/Account_Farming_Area__c.object
<CustomObject>
    <description>This object is to store the historical and current farming area data</description>
    <fields>
        <fullName>Area_Qty__c</fullName>
        <description>Farming Area of Grower(by crop)</description>
        <label>Agricultural Use Farming Area</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inbound_Area_Qty__c</fullName>
        <label>Inbound AgriculturalUse Farming Area Qty</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Farming Area</label>
        <referenceTo>Account_Farming_Area__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Farming Area</label>
    <nameField>
        <label>Account Farming Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Farming Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FarmingAreaValidationTriggerHandler_Test.cls
@isTest
public class FarmingAreaValidationTriggerHandler_Test {
    public static List<Account_Farming_Area__c> accTotalFarmingArea;
     @testSetup
    static void setup(){
        TestUtilClass.createtriggerControl();
         TestUtilClass.createCropRecordType();
        TestUtilClass.createTotalRecordType();
        TestUtilClass.createTestUsers('System Administrator',2);
        TestUtilClass.createTestAccount(10);
        TestUtilClass.createTestAccountRole(2);
        TestUtilClass.createTestTotalAccountFarmingArea(1);
        TestUtilClass.createTestCropAccountFarmingAreaInsert(5);
        TestUtilClass.createTestCropAccountFarmingArea(5);
        
        
       
    }
     static testMethod void testFarmingMethod(){
         List<Account_Farming_Area__c> accFarming = [Select id,Parent_SFID__c,  Inbound_Area_Qty__c,Area_Qty__c from Account_Farming_Area__c];
        // update accFarming;
         try{
         if(!accFarming.isEmpty()){
             for(Account_Farming_Area__c accFar : accFarming){
                 if(accFar.Parent_SFID__c != null){
                     accFar.Inbound_Area_Qty__c = 20200;
                     accFar.Area_Qty__c = 20000;
                 }
             }
         }
         update accFarming;
         }         
         
          catch(Exception e){
            System.debug('Exception Occured when createTestAccountCommunication'+e.getMessage());
        }

    }
}