src/objects/Account_Farming_Area__c.object
<CustomObject>
    <description>This object is to store the historical and current farming area data</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>to describe whether it&apos;s a Grower/Dealer</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account to which the Farming area is referring to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Area_Usage_Descr__c</fullName>
        <label>Agricultural Usage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa/Lucerne</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Area_Qty__c</fullName>
        <label>Inbound AgriculturalUse Farming Area Qty</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inbound_Area_Use_UOM_Descr__c</fullName>
        <label>Inbound Farming Area UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Hectare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Total_Farm_Area_Qty__c</fullName>
        <label>Inbound Total Farming Area Qty</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPS__c</fullName>
        <label>NPS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Farming Area</label>
        <referenceTo>Account_Farming_Area__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFM_Score__c</fullName>
        <label>RFM Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Very High</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017 Safra</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2017 Safrinha</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Sarfrinha</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safrinha</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
                <value>
                    <fullName>SPRING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Type__c</fullName>
        <description>This field is to specify the year type</description>
        <label>Year Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fiscal Year</fullName>
                </value>
                <value>
                    <fullName>Crop Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Farming Area</label>
    <nameField>
        <label>Account Farming Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Farming Areas</pluralLabel>
    <recordTypes>
        <fullName>Account_Farming_Area_Crop_Farming_Area</fullName>
        <active>true</active>
        <description>This record type is to store crop Farming Area data</description>
        <label>Crop Farming Area</label>
    </recordTypes>
    <recordTypes>
        <fullName>Account_Farming_Area_Total_Farming_Area</fullName>
        <active>true</active>
        <description>This record type is to store Total Farming Area data.</description>
        <label>Total Farming Area</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_GrowerProfileController.cls
public class Test_GrowerProfileController {
    @AuraEnabled    
    public static String GrowerFarmSizeDetails(Id growerAccId,String fiscalyr,String uom){
        system.debug('uom' + uom);
      GrowerAccountDataWrapper accountData = new GrowerAccountDataWrapper();
        List<Integer> areaShareList = new  List<Integer>();
     Integer areaMonShareTotal=0;
        Integer areaMonTotal=0;
        Id recordTypeId =[select id from Recordtype where Developername='Account_Farming_Area_Total_Farming_Area' LIMIT 1].id;
        system.debug('recordTypeId' +recordTypeId);
      List<Account_Farming_Area__c> accFarmingArea = new List<Account_Farming_Area__c>();
        String queryString= 'SELECT Id, Name,Account_SFID__c, Account_Business_Role_SFID__c, Parent_SFID__c,Area_Usage_Descr__c,Inbound_Area_Qty__c,Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c,Parent_SFID__r.Selling_Season_Descr__c,Inbound_Area_Use_UOM_Descr__c,Year__c, Year_Type__c From Account_Farming_Area__c Where Parent_SFID__c!=null AND Parent_SFID__r.Account_SFID__c =: growerAccId';  
        if(fiscalyr ==null ||fiscalyr=='FY17' ){
           queryString += ' AND Parent_SFID__r.Year__c=2017';
        }
        if(fiscalyr=='FY16' ){
           queryString += ' AND Parent_SFID__r.Year__c=2017'; 
        }
        accFarmingArea =Database.query(queryString);
        system.debug('-----' +queryString);
        system.debug('accFarmingArea' + accFarmingArea.size()) ;
        for(Integer i=0;i<accFarmingArea.size();i++){
           Integer areaMonsatoShare = Integer.valueOf((accFarmingArea[i].Inbound_Area_Qty__c/accFarmingArea[i].Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c)*100);
             areaMonShareTotal = areaMonShareTotal +areaMonsatoShare; 
             areaMonTotal = areaMonTotal + Integer.valueOf((accFarmingArea[i].Inbound_Area_Qty__c));
            areaShareList.add(areaMonsatoShare);
        }
        for(Integer i=0;i<areaShareList.size() && i<accFarmingArea.size();i++){
          accountData.Labels.add(areaShareList[i] + '% |' +accFarmingArea[i].Area_Usage_Descr__c+ ': ' + accFarmingArea[i].Inbound_Area_Qty__c +'' + accFarmingArea[i].Inbound_Area_Use_UOM_Descr__c) ; 
          accountData.growerAccountCroparea.add(areaShareList[i]);
        }
        accountData.othersShare=100 - areaMonShareTotal;
        accountData.othersArea=(Integer.valueOf((accFarmingArea[0].Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c)))- areaMonTotal;
        if(accountData.othersShare != 0){
       accountData.Labels.add(accountData.othersShare + '% |' +'Others'+ ': ' + accountData.othersArea +'' + 'Acre') ; 
        accountData.growerAccountCroparea.add(accountData.othersShare);
        }
        
        system.debug('areaShareList' +areaShareList);
        system.debug('accountData.Labels' +accountData.Labels[0]);
        for(Account_Farming_Area__c accfarming :accFarmingArea){
            accountData.growerAccountTotalArea=Integer.valueOf((accfarming.Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c));
        }
        
        
      return JSON.serialize(accountData);
    }
    
    @AuraEnabled    
    public static void getupdateFYArea(Id growerAccId,String crop1select,String crop2select, String crop3select,Integer totalArea, Integer  cornArea,Integer soyArea, Integer cottonArea, String seasonKey){
      List<Account_Farming_Area__c> accFarmingArea = new List<Account_Farming_Area__c>();
        List<Account_Farming_Area__c> accFarmupd = new List<Account_Farming_Area__c>();
        accFarmingArea = [SELECT Id, Name,Account_SFID__c, Account_Business_Role_SFID__c, Parent_SFID__c,Area_Usage_Descr__c,Inbound_Area_Qty__c,Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c,Parent_SFID__r.Selling_Season_Descr__c,Inbound_Area_Use_UOM_Descr__c,
                          RFM_Score__c, Selling_Season_Descr__c, Year__c, Year_Type__c, NPS__c From Account_Farming_Area__c Where RecordType.DeveloperName='Account_Farming_Area_Crop_Farming_Area' AND Parent_SFID__r.Account_SFID__c =: growerAccId];
      system.debug('accFarmingArea' + accFarmingArea) ;
	  for(Account_Farming_Area__c accFarmSize : accFarmingArea){
		if(crop1select == accFarmSize.Area_Usage_Descr__c){
			accFarmSize.Inbound_Area_Qty__c = cornArea;
		}
		if(crop2select == accFarmSize.Area_Usage_Descr__c){
			accFarmSize.Inbound_Area_Qty__c = soyArea;
		}
		if(crop2select == accFarmSize.Area_Usage_Descr__c){
			accFarmSize.Inbound_Area_Qty__c = cottonArea;
		}
		accFarmSize.Parent_SFID__r.Inbound_Total_Farm_Area_Qty__c = totalArea;
		accFarmupd.add(accFarmSize);
          System.debug('accFarmupd' + accFarmupd[0]);
	  }
	  update accFarmupd;
    }

    
    class GrowerAccountDataWrapper{
        public List<String> Labels {get;set;}
        public String growerAccountName {get;set;}
        public String growerAccountRADL {get;set;}
        public String growerPrimaryContactFirstName {get;set;}
        public String growerPrimaryContactLastName {get;set;}
        public String growerPrimaryContactEmail {get;set;}
        public String growerPrimaryContactPhone {get;set;}
        public String growerAddressLine {get;set;}
        Public String growerAreaTotal{get;set;} 
        public String phone{get;set;}	
        public String email{get;set;} 
        public List<String> growerSeason{get;set;}
        public String growercrop {get;set;}  
        public string growerRADL{get;set;}
        public string growerCornRADL{get;set;}
        public string growerSoyRADL{get;set;}
        public Integer growerAccountTotalArea{get;set;}
        public List<Integer> growerAccountCroparea{get;set;}

        public List<String> growerbrand {get;set;}
        public List<String> growerFamily {get;set;}
        public List<String> areaMonShare {get;set;}
        public Integer othersShare {get;set;}
        public Integer othersArea {get;set;}   
        public List<Integer> chartdata {get;set;}
        public Boolean displayMsg {get;set;}
        public List<String> buttonValue {get;set;}
        public GrowerAccountDataWrapper(){
            
            Labels = new List<String>();
            growerSeason=new List<String>();
            growerbrand = new List<String>();
            growerFamily = new List<String>();
            chartdata = new List<Integer>();
            areaMonShare = new List<String>();
            buttonValue =new List<String>();
            growerAccountCroparea=new List<Integer>();
        }
    }

}