src/objects/Account_Farming_Area__c.object
<CustomObject>
    <description>This object is to store the historical and current farming area data</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>to describe whether it&apos;s a Grower/Dealer</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account to which the Farming area is referring to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Date__c</fullName>
        <label>Archive Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>To describe the status of the record</description>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area_Qty__c</fullName>
        <description>Farming Area of Grower(by crop)</description>
        <label>Agricultural Use Farming Area</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area_Updated_DateTime__c</fullName>
        <description>Last updated on</description>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Area_Usage_Descr__c</fullName>
        <label>Agricultural Usage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corn</fullName>
                </value>
                <value>
                    <fullName>Sorghum</fullName>
                </value>
                <value>
                    <fullName>Cotton</fullName>
                </value>
                <value>
                    <fullName>Alfalfa/Lucerne</fullName>
                </value>
                <value>
                    <fullName>Sudan/Sudax</fullName>
                </value>
                <value>
                    <fullName>Oats</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Services</fullName>
                </value>
                <value>
                    <fullName>Potato</fullName>
                </value>
                <value>
                    <fullName>Lupines</fullName>
                </value>
                <value>
                    <fullName>Sugarbeet</fullName>
                </value>
                <value>
                    <fullName>CORN AND COTTON</fullName>
                </value>
                <value>
                    <fullName>Canola/Oilseed Rape</fullName>
                </value>
                <value>
                    <fullName>Rye</fullName>
                </value>
                <value>
                    <fullName>Wheat</fullName>
                </value>
                <value>
                    <fullName>Grass/Turf/Lawn</fullName>
                </value>
                <value>
                    <fullName>Sunflower</fullName>
                </value>
                <value>
                    <fullName>Barley</fullName>
                </value>
                <value>
                    <fullName>Seed Other</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Seed</fullName>
                </value>
                <value>
                    <fullName>Sugarcane</fullName>
                </value>
                <value>
                    <fullName>Triticale</fullName>
                </value>
                <value>
                    <fullName>Rice</fullName>
                </value>
                <value>
                    <fullName>Soy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_Usage_UOM_Descr__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acres</fullName>
                </value>
                <value>
                    <fullName>Hectares</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Area_Qty__c</fullName>
        <label>Inbound AgriculturalUse Farming Area Qty</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inbound_Area_Use_UOM_Descr__c</fullName>
        <label>Inbound Farming Area UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Hectare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inbound_Total_Farm_Area_Qty__c</fullName>
        <label>Inbound Total Farming Area Qty</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account Farming Area</label>
        <referenceTo>Account_Farming_Area__c</referenceTo>
        <relationshipLabel>Account Farming Areas</relationshipLabel>
        <relationshipName>Account_Farming_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Season_Descr__c</fullName>
        <label>Selling Season</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017 Safra</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2017 Safrinha</fullName>
                </value>
                <value>
                    <fullName>2016 Safra</fullName>
                </value>
                <value>
                    <fullName>2016 Sarfrinha</fullName>
                </value>
                <value>
                    <fullName>2015 Safra</fullName>
                </value>
                <value>
                    <fullName>2015 Safrinha</fullName>
                </value>
                <value>
                    <fullName>SUMMER</fullName>
                </value>
                <value>
                    <fullName>WINTER</fullName>
                </value>
                <value>
                    <fullName>SPRING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>This field is to specify the level of service to be delivered to customer</description>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Farming_Area_Qty__c</fullName>
        <label>Total Farming Area</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_Type__c</fullName>
        <description>This field is to specify the year type</description>
        <label>Year Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fiscal Year</fullName>
                </value>
                <value>
                    <fullName>Crop Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Farming Area</label>
    <nameField>
        <label>Account Farming Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Farming Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recordtypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Recordtypes</label>
</CustomObject>

src/classes/FarmingAreaValidationTriggerHandler.cls
public class FarmingAreaValidationTriggerHandler {
    public static void onBeforeInsertOrUpdate(List<Account_Farming_Area__c> listFarmingAreaRecords, String triggerContext,Map<Id,Account_Farming_Area__c> OldMap)
    {
        
        // Query CROP Farming Area and Total Farm Area Record Type.
        Id croprecordTypeId;
        set<Id> parentFarmingIdSet = new Set<Id>();
        Recordtypes__c croprecordType = Recordtypes__c.getValues('AccountFarmingAreaCropFarmingArea');
        Recordtypes__c parentFarmrecordType = Recordtypes__c.getValues('AccountFarmingAreaTotalFarmingArea');
        Set<Id> entryParentRecordIds = new Set<Id>();       
        Map<Id,Integer> childRecordMap = new Map<Id,Integer>();
        Map<String,String> parentFarmRecordMap = new Map<String,String>();
        Map<Id,String> parentTotalFarmRecordMap = new Map<Id,String>();
        Set<String> farmingAreaIds = new Set<String>(); 
        List<Account_Farming_Area__c> listParentFarmingAreaRecords = new List<Account_Farming_Area__c>();
        List<Account_Farming_Area__c> listchildCropFarmingRecords = new List<Account_Farming_Area__c>();
        
        Map<Id, Account_Farming_Area__c> mapParentFarmingAreaRecords = new Map<Id, Account_Farming_Area__c>();        
        
        Integer count = 0;
        for(Account_Farming_Area__c farmingRecord : listFarmingAreaRecords){
            if(triggerContext == 'isUpdate' && !OldMap.isEmpty() && farmingRecord.RecordTypeId == parentFarmrecordType.Value__c && OldMap.containsKey(farmingRecord.Id)
               && ((OldMap.get(farmingRecord.Id).Inbound_Total_Farm_Area_Qty__c != farmingRecord.Inbound_Total_Farm_Area_Qty__c) ||
              ((OldMap.get(farmingRecord.Id).Total_Farming_Area_Qty__c == Null && farmingRecord.Total_Farming_Area_Qty__c != Null) 
               || (OldMap.get(farmingRecord.Id).Total_Farming_Area_Qty__c != Null && OldMap.get(farmingRecord.Id).Total_Farming_Area_Qty__c != farmingRecord.Total_Farming_Area_Qty__c)))){
                   parentTotalFarmRecordMap.put(farmingRecord.Id,farmingRecord.Inbound_Total_Farm_Area_Qty__c + ':'+farmingRecord.Total_Farming_Area_Qty__c);
            }
            
            if(farmingRecord.Parent_SFID__c != null && farmingRecord.RecordTypeId == croprecordType.Value__c){
                if(!parentFarmRecordMap.containskey(farmingRecord.Parent_SFID__c)){
                    parentFarmRecordMap.put(farmingRecord.Parent_SFID__c,farmingRecord.Inbound_Area_Qty__c + ':'+farmingRecord.Area_Qty__c);
                }
                else if(parentFarmRecordMap.containskey(farmingRecord.Parent_SFID__c))  {
                    farmingAreaIds.add(farmingRecord.Parent_SFID__c);
                    String inputVal = parentFarmRecordMap.get(farmingRecord.Parent_SFID__c);
                    if(farmingRecord.Inbound_Area_Qty__c != Null){
                        inputVal = Double.valueof(inputVal.split(':')[0]) + farmingRecord.Inbound_Area_Qty__c + ':' + inputVal.split(':')[1];
                    }
                    if(farmingRecord.Area_Qty__c != Null){
                        inputVal =   inputVal.split(':')[0] + ':' + ((inputVal.split(':')[1] != 'null'? Double.valueof(inputVal.split(':')[1]) : 0) + farmingRecord.Area_Qty__c);
                    }
                    parentFarmRecordMap.put(farmingRecord.Parent_SFID__c,inputVal);
                    
                }
                listchildCropFarmingRecords.add(farmingRecord);   
            }
        }
        // Querying all the total farming records
        listParentFarmingAreaRecords = [SELECT Id, RecordTypeId, Account_SFID__c, Account_Business_Role_SFID__c, Area_Usage_Descr__c, Area_Qty__c, Inbound_Area_Qty__c, Archive_Date__c,
                                        Archive_Ind__c, Area_Updated_DateTime__c, Parent_SFID__c,Service_Level_Class_Descr__c, Selling_Season_Descr__c,
                                        Total_Farming_Area_Qty__c, Inbound_Total_Farm_Area_Qty__c, Area_Usage_UOM_Descr__c, Year__c, Year_Type__c,Inbound_Area_Use_UOM_Descr__c
                                        FROM Account_Farming_Area__c WHERE Id IN : parentFarmRecordMap.keySet()];
        for(Account_Farming_Area__c totalFarmRecord : listParentFarmingAreaRecords) {
            if(!parentTotalFarmRecordMap.isEmpty() && parentTotalFarmRecordMap.containsKey(totalFarmRecord.Id)) {
                totalFarmRecord.Inbound_Total_Farm_Area_Qty__c =  (parentTotalFarmRecordMap.get(totalFarmRecord.Id).split(':')[0] != 'null' ? Integer.valueOf(parentTotalFarmRecordMap.get(totalFarmRecord.Id).split(':')[0]):totalFarmRecord.Inbound_Total_Farm_Area_Qty__c);
                totalFarmRecord.Total_Farming_Area_Qty__c =  (parentTotalFarmRecordMap.get(totalFarmRecord.Id).split(':')[1] != 'null' ? Integer.valueOf(parentTotalFarmRecordMap.get(totalFarmRecord.Id).split(':')[1]):totalFarmRecord.Total_Farming_Area_Qty__c);
              }
            
            mapParentFarmingAreaRecords.put(totalFarmRecord.Id, totalFarmRecord);            
        }
        if(!listchildCropFarmingRecords.isEmpty() && mapParentFarmingAreaRecords.size() > 0){
            FarmingAreaValidationTriggerHelper.validateCROPFarmAreaVSTotalFarmArea(listchildCropFarmingRecords, mapParentFarmingAreaRecords,parentFarmRecordMap,triggerContext);       
        }
    }
}