src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Business_Role__c.object
<CustomObject>
    <description>Business Roles associated with an Account in which additional Business Role specific attributes need to be captured.</description>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Business Role</description>
        <inlineHelpText>Account related to the Business Role</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Business_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Descr__c</fullName>
        <description>Busines Unit/Line of Business associated with the Role.  Not all areas will have need to call out a specific line of business.  Example: &quot;Ag Chem&quot;, &quot;National&quot;, &quot;Channel&quot;, etc.</description>
        <inlineHelpText>Busines Unit/Line of Business associated with the Role.</inlineHelpText>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Seed and Traits</fullName>
                </value>
                <value>
                    <fullName>Agroceres</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Unit/Business Role etc. related to Account Business Role</description>
        <label>Parent Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Business Roles</relationshipLabel>
        <relationshipName>Account_Business_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Category_Descr__c</fullName>
        <description>Company level description of an Account&apos;s relationship to Monsanto.  Terminiology to be determined by Monsanto Global business.  For example, they may use the term &quot;Partner&quot; to represent an account that is the intermediary between Monsanto and the end consumer regardless of the specific business model.

Per discussion with Tony Rizzo, recommend to stick with ACS terminology of &quot;Partner&quot; and &quot;Customer&quot;.</description>
        <inlineHelpText>Company high level description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
                <value>
                    <fullName>Intermediary</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Finer role definition of Account&apos;s relationship to Monsanto.  Terminology to be determined.  For example, &quot;Partner&quot; at the company level may be refered to within the region as a &quot;Agent&quot;, &quot;Dealer&quot;, &quot;Retailer&quot;, &quot;Distributer&quot;, etc.</description>
        <inlineHelpText>Company description of an Account&apos;s relationship to Monsanto.</inlineHelpText>
        <label>Business Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Level_Class_Descr__c</fullName>
        <description>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role.  This is used to help the user determine the level of service requirements for the specific account.</description>
        <inlineHelpText>&quot;Retain&quot;, &quot;Aquire&quot;, &quot;Develop&quot;, or &quot;Light Touch&quot; Sales and Marketing Service Level Classification assigned to the Account Business Role</inlineHelpText>
        <label>RADL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquire</fullName>
                </value>
                <value>
                    <fullName>Develop</fullName>
                </value>
                <value>
                    <fullName>Light Touch</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retain</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Business Role</label>
    <nameField>
        <displayFormat>ABR-{0}</displayFormat>
        <label>Business Role Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Business Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Communication__c.object
<CustomObject>
    <description>Link Accounts to their associated Addresses, Phone Numbers, Emails, etc..  Many-to-many relationship.</description>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</description>
        <inlineHelpText>Business Role Lookup associated with the Account&apos;s Address/Phone/Email/etc.</inlineHelpText>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account related to the Communication</description>
        <inlineHelpText>Account related to the Communication</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Communications</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <description>&quot;Y&quot; Indicates that the record is ready for archival.</description>
        <inlineHelpText>&quot;Y&quot; indicates record is ready for archival.</inlineHelpText>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Name__c</fullName>
        <description>City Name</description>
        <inlineHelpText>City Name</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country Name</description>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Address/Phone/Email/etc. related to the Account Communication Role</description>
        <inlineHelpText>Account Address/Phone/Email/etc. related to the Account Communication Role</inlineHelpText>
        <label>Parent Account Communication</label>
        <referenceTo>Account_Communication__c</referenceTo>
        <relationshipLabel>Account Communication</relationshipLabel>
        <relationshipName>Account_Communications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Descr__c</fullName>
        <description>Role for the Account Communication</description>
        <inlineHelpText>Role for the Account Communication</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Name__c</fullName>
        <description>State Name</description>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Addr__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Communication</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Account Communication Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Communications</pluralLabel>
    <recordTypes>
        <fullName>Account_Communication_Address_Role_Business_Role</fullName>
        <active>true</active>
        <description>The record type for physical address&apos; role&apos;s Business Role.</description>
        <label>Address Role Business Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Identifier__c.object
<CustomObject>
    <fields>
        <fullName>Account_Business_Role_SFID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field primarily indicates if it is a Grower or a Dealer and the brand if applicable.</description>
        <label>Account Business Role</label>
        <referenceTo>Account_Business_Role__c</referenceTo>
        <relationshipLabel>Account Identifiers</relationshipLabel>
        <relationshipName>Account_Identifiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_SFID__c</fullName>
        <description>Account to which the Identifier maps to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Identifiers</relationshipLabel>
        <relationshipName>Account_Identifiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <label>Archive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_ID__c</fullName>
        <description>Unique identifier fro an account from the source system</description>
        <externalId>true</externalId>
        <label>Identifier</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Account Identifier</label>
    <nameField>
        <label>Account Identifier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Identifiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Archive_Ind__c</fullName>
        <label>Archive Ind</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Frontier_LookUpController.cls
public class Frontier_LookUpController {
    
     /*
     * Loads the initial value of the given SObject type with ID "value"
	 */
	@AuraEnabled
    public static String getCurrentValue(String type, String value){
        if(String.isBlank(type)){
            return null;
        }
        
        ID lookupId = null;
        try{   
        	lookupId = (ID)value;
        }catch(Exception e){
            return null;
        }
        
        if(String.isBlank(lookupId)){
            return null;
        }
        
        SObjectType objType = Schema.getGlobalDescribe().get(type);
        if(objType == null){
            return null;
        }

        String nameField = getSobjectNameField(objType);
        String query = 'Select Id, '+nameField+' From '+type+' Where Id = \''+lookupId+'\'';
        System.debug('### Query: '+query);
        List<SObject> oList = Database.query(query);
        if(oList.size()==0) {
            return null;
        }
		return (String) oList[0].get(nameField);
    }
    
    /*
     * Utility class for search results
	*/
    /*public class SearchResult{
        public String name{get;Set;}
        public String id{get;set;}
        public String email{get;set;}
    }*/
    
    /*
     * Returns the "Name" field for a given SObject (e.g. Case has CaseNumber, Account has Name)
	*/
    private static String getSobjectNameField(SobjectType sobjType){
        
        //describes lookup obj and gets its name field
        String nameField = 'Name';
        Schema.DescribeSObjectResult dfrLkp = sobjType.getDescribe();
        for(schema.SObjectField sotype : dfrLkp.fields.getMap().values()){
            Schema.DescribeFieldResult fieldDescObj = sotype.getDescribe();
            if(fieldDescObj.isNameField() ){
            	nameField = fieldDescObj.getName();
                break;
            }
        }
        return nameField;
    }
	
    /*
     * Searchs (using SOSL) for a given Sobject type
     */
    @AuraEnabled
    public static String searchSObject(String type, String searchString,string condition,string fields,string searchfield, boolean isCustomQuery,String customQueryWhere){
        
        string conditions = condition != ''? ' '+condition+' ' : '';
        if(String.isBlank(type) || String.isBlank(searchString)){
            return null;
        }
        
        SObjectType objType = Schema.getGlobalDescribe().get(type);
        if(objType == null){
            return null;
        }        
        //String nameField = getSobjectNameField(objType);
        
        if(isCustomQuery){
            String accListQuery,finalwhere;
            
            Set<Id> accountIds =  new Set<Id>();
            Set<Id> territoryaccIds = new Set<Id>();

           	List<Account_Business_Role__c> accountRecordsList = new List<Account_Business_Role__c>();
            
            System.debug('accountTypeinLookup' +customQueryWhere);
            
            if(customQueryWhere != null){
                if(customQueryWhere == 'Dealer' || String.valueof(customQueryWhere).replaceAll( '\\s+', '') == 'Dealer-Dealer'){
                    finalwhere = ' AND (Role_Descr__c = \'Partner\')';
                }
                else if(customQueryWhere == 'Grower' || customQueryWhere.contains('Grower')){
                    finalwhere =  ' AND (Role_Descr__c=\'Customer\' AND Role_Category_Descr__c = \'Consumer\' AND Business_Unit_Descr__c = \'Customer\')';
                }
                else if(customQueryWhere == 'Both'){
                    finalwhere = ' AND ((Role_Descr__c = \'Partner\') OR (Role_Descr__c=\'Customer\' AND Role_Category_Descr__c = \'Consumer\' AND Business_Unit_Descr__c = \'Customer\'))';
                }
                
            }
			
            System.debug('finalwhereinLookup' +finalwhere);
            territoryaccIds = Util.getTerritoryAccountIds();		

            accListQuery = 'SELECT Account_SFID__c,Account_SFID__r.Name,Service_Level_Class_Descr__c,'                                
                +'Role_Descr__c,Business_Unit_Descr__c,' 
                +'(SELECT Source_System_ID__c FROM Account_Identifiers__r LIMIT 1),'
                +'(SELECT Parent_SFID__r.Parent_SFID__r.Id,Parent_SFID__r.Parent_SFID__r.Street_Addr__c,Parent_SFID__r.Parent_SFID__r.City_Name__c,'      
                +'Parent_SFID__r.Parent_SFID__r.State_Name__c,Parent_SFID__r.Parent_SFID__r.Country_Name__c,'   
                +'Parent_SFID__r.Role_Descr__c FROM Account_Communications__r' 
                +' WHERE   Archive_Ind__c = \'N\' AND  Parent_SFID__r.Archive_Ind__c = \'N\' AND   Parent_SFID__r.Parent_SFID__r.Archive_Ind__c = \'N\''
                +' AND   RecordType.DeveloperName = \'Account_Communication_Address_Role_Business_Role\' AND  Parent_SFID__r.Role_Descr__c = \'Business\''
                +' LIMIT 1)'
                +' FROM  Account_Business_Role__c'
                +' WHERE Account_SFID__c =: territoryaccIds'
                +' AND Archive_Ind__c = \'N\''
                +' AND   Account_SFID__r.Archive_Ind__c = \'N\'' + finalwhere + ' AND Account_SFID__r.Name LIKE \'%'+searchString+'%\' LIMIT 50';
            
            try{
                System.debug('accListQuery' + accListQuery);
                accountRecordsList = Database.query(accListQuery);
                System.debug('accountRecordsList' + accountRecordsList);
            }
            catch(Exception e){
                system.debug('Error Occured on getting the account communication detais. =========>'+e.getMessage());
            }  
            
            for(Account_Business_Role__c accRoleList : accountRecordsList){
                accountIds.add(accRoleList.Account_SFID__c);
            }
            
            searchString = '\'*'+searchString+'*\'';
            String soslQuery = 'FIND :searchString IN '+searchfield+' FIELDS RETURNING '
                + type +'(Id,'+fields+' Where Id IN :accountIds ORDER BY '+searchfield+') LIMIT 20';
            System.debug('SOSL QUERY: '+soslQuery);
            List<List<SObject>> results =  Search.query(soslQuery);
            
            system.debug('results[0]=>'+results[0]);
            return JSON.serialize(results[0]);
        }
        else{
            searchString = '\'*'+searchString+'*\'';
            String soslQuery = 'FIND :searchString IN '+searchfield+' FIELDS RETURNING '
                + type +'(Id,'+fields+conditions+' ORDER BY '+searchfield+') LIMIT 20';
            System.debug('SOSL QUERY: '+soslQuery);
            List<List<SObject>> results =  Search.query(soslQuery);
            
            /*List<SearchResult> output = new List<SearchResult>();
            if(results.size()>0){
                for(SObject sobj : results[0]){
                    SearchResult sr = new SearchResult();
                    sr.id = (String)sobj.get('Id');
                    sr.Name = (String)sobj.get('name');
                    sr.email = (String)sobj.get('email');
                    output.add(sr)   ;
                }
            }*/
            system.debug('results[0]=>'+results[0]);
            return JSON.serialize(results[0]);
        }
    }

}